-- Corrige ambiguidade entre variável a%ROWTYPE e alias SQL da migração 219.
CREATE OR REPLACE FUNCTION conferir_permuta_servico() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a "AcordoPermutaServico"%ROWTYPE; p "PropostaCompensacaoPermuta"%ROWTYPE; u "Usuario"%ROWTYPE; limite DECIMAL(12,2); comprovado DECIMAL(12,2);
BEGIN
 IF TG_TABLE_NAME='AcordoPermutaServico' THEN
  SELECT * INTO u FROM "Usuario" WHERE id=NEW."preparadorId" FOR SHARE;
  IF NEW."vigenciaFim"<NEW."vigenciaInicio" OR NEW."quantidadePactuada"<=0 OR NEW."valorPorUnidade"<=0 OR NEW."valorTotalPactuado" IS DISTINCT FROM round(NEW."quantidadePactuada"*NEW."valorPorUnidade",2) OR btrim(NEW.moeda)='' OR btrim(NEW.contrapartida)='' OR btrim(NEW."formulaDescricao")='' OR NOT FOUND OR NOT u.ativo OR NOT ('FINANCEIRO'=ANY(u.papeis) OR 'ADMINISTRADOR'=ANY(u.papeis)) THEN RAISE EXCEPTION 'Acordo de permuta inválido'; END IF;
 ELSIF TG_TABLE_NAME='AcordoPermutaCobranca' THEN
  SELECT * INTO a FROM "AcordoPermutaServico" WHERE id=NEW."acordoId" FOR UPDATE;
  IF EXISTS (SELECT 1 FROM "ConfirmacaoServicoPermuta" WHERE "acordoId"=NEW."acordoId") OR NEW."valorMaximo"<=0 OR NOT EXISTS (SELECT 1 FROM "Cobranca" c WHERE c.id=NEW."cobrancaId" AND c."matriculaId"=a."matriculaId" AND c.moeda=a.moeda AND c.tipo='MENSALIDADE'::"TipoCobranca" AND c.status IN ('PENDENTE','ATRASADO')) THEN RAISE EXCEPTION 'Elegibilidade fechada ou inválida'; END IF;
 ELSIF TG_TABLE_NAME='ConfirmacaoServicoPermuta' THEN
  SELECT * INTO a FROM "AcordoPermutaServico" WHERE id=NEW."acordoId" FOR UPDATE; SELECT * INTO u FROM "Usuario" WHERE id=NEW."confirmadorId" FOR SHARE;
  IF NOT FOUND OR NOT u.ativo OR NOT ('GERENTE_PEDAGOGICO'=ANY(u.papeis) OR 'ADMINISTRADOR'=ANY(u.papeis)) OR NEW."periodoFim"<NEW."periodoInicio" OR NEW."periodoInicio"<a."vigenciaInicio" OR NEW."periodoFim">a."vigenciaFim" OR NEW."quantidadeComprovada"<=0 OR btrim(NEW."referenciaServico")='' OR btrim(NEW.evidencia)='' OR EXISTS (SELECT 1 FROM "ConfirmacaoServicoPermuta" c WHERE c."acordoId"=NEW."acordoId" AND c."periodoInicio"<=NEW."periodoFim" AND NEW."periodoInicio"<=c."periodoFim") OR NEW."quantidadeComprovada" + COALESCE((SELECT sum(c."quantidadeComprovada") FROM "ConfirmacaoServicoPermuta" c WHERE c."acordoId"=NEW."acordoId"),0)>a."quantidadePactuada" THEN RAISE EXCEPTION 'Confirmação de permuta inválida'; END IF;
 ELSIF TG_TABLE_NAME='PropostaCompensacaoPermuta' THEN
  SELECT c."quantidadeComprovada",acordo_linha."valorPorUnidade" INTO comprovado,limite FROM "ConfirmacaoServicoPermuta" c JOIN "AcordoPermutaServico" acordo_linha ON acordo_linha.id=c."acordoId" WHERE c.id=NEW."confirmacaoId" FOR UPDATE OF c,acordo_linha; SELECT * INTO u FROM "Usuario" WHERE id=NEW."preparadorId" FOR SHARE;
  IF NOT FOUND OR NOT u.ativo OR NOT ('FINANCEIRO'=ANY(u.papeis) OR 'ADMINISTRADOR'=ANY(u.papeis)) OR NEW.valor<=0 OR NEW.valor>round(comprovado*limite,2) OR EXISTS (SELECT 1 FROM "PropostaCompensacaoPermuta" x LEFT JOIN "DecisaoCompensacaoPermuta" d ON d."propostaId"=x.id WHERE x."confirmacaoId"=NEW."confirmacaoId" AND (d.id IS NULL OR d.aprovada)) THEN RAISE EXCEPTION 'Proposta de permuta inválida ou já consumida'; END IF;
 ELSIF TG_TABLE_NAME='DestinoPropostaCompensacaoPermuta' THEN
  SELECT * INTO p FROM "PropostaCompensacaoPermuta" WHERE id=NEW."propostaId" FOR UPDATE;
  IF EXISTS (SELECT 1 FROM "DecisaoCompensacaoPermuta" WHERE "propostaId"=NEW."propostaId") OR NEW.valor<=0 OR NOT EXISTS (SELECT 1 FROM "ConfirmacaoServicoPermuta" c JOIN "AcordoPermutaCobranca" e ON e."acordoId"=c."acordoId" AND e."cobrancaId"=NEW."cobrancaId" WHERE c.id=p."confirmacaoId" AND NEW.valor<=e."valorMaximo") THEN RAISE EXCEPTION 'Destino fechado ou inválido'; END IF;
 ELSIF TG_TABLE_NAME='DecisaoCompensacaoPermuta' THEN
  SELECT * INTO p FROM "PropostaCompensacaoPermuta" WHERE id=NEW."propostaId" FOR UPDATE; SELECT * INTO u FROM "Usuario" WHERE id=NEW."decisorId" FOR SHARE;
  IF p.id IS NULL OR NOT u.ativo OR p."preparadorId"=NEW."decisorId" OR NOT ('ADMINISTRADOR'=ANY(u.papeis) OR ('FINANCEIRO'=ANY(u.papeis) AND 'financeiro.aprovar_acertos'=ANY(u.permissoes))) THEN RAISE EXCEPTION 'Decisão de permuta exige aprovador independente autorizado'; END IF;
  IF NEW.aprovada AND (NOT EXISTS (SELECT 1 FROM "DestinoPropostaCompensacaoPermuta" d WHERE d."propostaId"=p.id) OR p.valor IS DISTINCT FROM (SELECT sum(d.valor) FROM "DestinoPropostaCompensacaoPermuta" d WHERE d."propostaId"=p.id) OR EXISTS (SELECT 1 FROM "DestinoPropostaCompensacaoPermuta" destino JOIN "ConfirmacaoServicoPermuta" c ON c.id=p."confirmacaoId" JOIN "AcordoPermutaServico" acordo_linha ON acordo_linha.id=c."acordoId" LEFT JOIN "AcordoPermutaCobranca" elegivel ON elegivel."acordoId"=acordo_linha.id AND elegivel."cobrancaId"=destino."cobrancaId" LEFT JOIN "Cobranca" cobranca ON cobranca.id=destino."cobrancaId" WHERE destino."propostaId"=p.id AND (elegivel.id IS NULL OR cobranca."matriculaId"<>acordo_linha."matriculaId" OR cobranca.moeda<>acordo_linha.moeda OR cobranca.tipo IS DISTINCT FROM 'MENSALIDADE'::"TipoCobranca" OR cobranca.status NOT IN ('PENDENTE','ATRASADO') OR destino.valor>elegivel."valorMaximo"))) THEN RAISE EXCEPTION 'Decisão de permuta aprovada exige destinos ainda válidos'; END IF;
 END IF; RETURN NEW;
END $$;
