import { beforeEach, expect, it, vi } from "vitest";
const { authMock } = vi.hoisted(() => ({ authMock: vi.fn() }));
vi.mock("@/lib/auth", () => ({ auth: authMock }));
vi.mock("@/server/_shared", async (original) => {
  const real = await original<typeof import("@/server/_shared")>();
  return { ...real, exigirSessaoComPapel: async (...papeis: import("@prisma/client").Papel[]) => {
    const session = await authMock();
    const u = await prisma.usuario.findUniqueOrThrow({ where: { id: session.user.id }, select: { id: true, nome: true, papeis: true, ativo: true } });
    if (!u.ativo) throw new real.ErroPermissao();
    real.exigirPapel(u, ...papeis); return u;
  } };
});
import { prepararCompensacaoCobertura, decidirCompensacaoCobertura } from "./compensacao-cobertura";
import { prisma } from "@/lib/prisma";
import { criarUsuario, seedCatalogoMinimo, truncarBanco } from "@/test/integracao";
import { seedRelatoOfertaConfirmado } from "@/test/indisponibilidade-oferta";
let origem: { matriculaId: string; cobrancaOrigemId: string; preparadorId: string; motivo: string; evidenciaCondicoes: string; diasPropostos: string[]; coberturaOriginalInicio: Date; coberturaOriginalFim: Date; valorCoberturaOriginal: number; moeda: string; cobrancaVersao: number }, decisorId: string, outraMatriculaId: string;
beforeEach(async () => {
  await truncarBanco(); const cat = await seedCatalogoMinimo();
  const preparador = await criarUsuario(["FINANCEIRO"]); decisorId = (await criarUsuario(["ADMINISTRADOR"])).id;
  const aluno = await prisma.aluno.create({ data: { primeiroNome: "Compensação teste", paisId: cat.pais.id } });
  const criar = () => prisma.matricula.create({ data: { alunoId: aluno.id, produtoId: cat.produto.id, paisId: cat.pais.id, moeda: "CRC", status: "ATIVA" } });
  const m = await criar(); outraMatriculaId = (await criar()).id;
  await seedRelatoOfertaConfirmado(m.id, "2026-09-10", "2026-09-13");
  const c = await prisma.cobranca.create({ data: { matriculaId: m.id, tipo: "MENSALIDADE", moeda: "CRC", valorOriginal: 300, valorNegociado: 300, vencimento: new Date("2026-09-05"), coberturaInicio: new Date("2026-09-01"), coberturaFim: new Date("2026-09-30") } });
  origem = { matriculaId: m.id, cobrancaOrigemId: c.id, preparadorId: preparador.id, motivo: "Indisponibilidade documentada", evidenciaCondicoes: "Condições do contrato conferidas", diasPropostos: ["2026-09-10", "2026-09-11"], coberturaOriginalInicio: new Date("2026-09-01"), coberturaOriginalFim: new Date("2026-09-30"), valorCoberturaOriginal: 300, moeda: "CRC", cobrancaVersao: c.versao };
});
it("banco exige cobrança do mesmo contrato e aprovação por outra pessoa", async () => {
  await expect(prisma.compensacaoCoberturaMatricula.create({ data: { ...origem, matriculaId: outraMatriculaId } })).rejects.toThrow();
  const c = await prisma.compensacaoCoberturaMatricula.create({ data: origem });
  await expect(prisma.compensacaoCoberturaMatricula.update({ where: { id: c.id }, data: { status: "APROVADA", decisorId: origem.preparadorId, decididaEm: new Date(), motivoDecisao: "Conferido" } })).rejects.toThrow();
  await expect(prisma.diaCompensacaoCobertura.create({ data: { compensacaoId: c.id, matriculaId: origem.matriculaId, diaOrigem: new Date("2026-09-10") } })).rejects.toThrow();
});
it("um dia aprovado não pode ser duplicado nem destinado sem referência", async () => {
  const c = await prisma.compensacaoCoberturaMatricula.create({ data: { ...origem, status: "APROVADA", decisorId, decididaEm: new Date(), motivoDecisao: "Conferência independente" } });
  const data = { compensacaoId: c.id, matriculaId: origem.matriculaId, diaOrigem: new Date("2026-09-10") };
  const dia = await prisma.diaCompensacaoCobertura.create({ data });
  await expect(prisma.diaCompensacaoCobertura.create({ data })).rejects.toThrow();
  await expect(prisma.diaCompensacaoCobertura.create({ data: { ...data, diaOrigem: new Date("2026-09-12") } })).rejects.toThrow();
  await expect(prisma.diaCompensacaoCobertura.update({ where: { id: dia.id }, data: { estado: "RECOMPOSTO" } })).rejects.toThrow();
  await prisma.diaCompensacaoCobertura.update({ where: { id: dia.id }, data: { estado: "RECOMPOSTO", destinacaoReferencia: "cobertura-aprovada-teste", destinadoEm: new Date(), versao: { increment: 1 } } });
  expect((await prisma.diaCompensacaoCobertura.findUniqueOrThrow({ where: { id: dia.id } })).versao).toBe(2);
  await expect(prisma.diaCompensacaoCobertura.update({ where: { id: dia.id }, data: { estado: "LIQUIDADO_FINANCEIRAMENTE", destinacaoReferencia: "acerto-teste", versao: { increment: 1 } } })).rejects.toThrow();
  await expect(prisma.diaCompensacaoCobertura.delete({ where: { id: dia.id } })).rejects.toThrow();
  await expect(prisma.compensacaoCoberturaMatricula.update({ where: { id: c.id }, data: { valorCoberturaOriginal: 200 } })).rejects.toThrow();
  await expect(prisma.cobranca.delete({ where: { id: origem.cobrancaOrigemId } })).rejects.toThrow();
});

it("ações conferem a origem e exigem permissão e decisão independente antes de gerar dias", async () => {
  const doc = await prisma.documento.create({ data: { matriculaId: origem.matriculaId, categoria: "CONTRATO", nome: "Contrato fictício", url: "/api/files/compensacao.pdf" } });
  await prisma.matricula.update({ where: { id: origem.matriculaId }, data: { contratoOk: true, confirmacaoContratoEm: new Date(), confirmacaoContratoPorId: origem.preparadorId, contratoDocumentoId: doc.id } });
  await prisma.cobranca.update({ where: { id: origem.cobrancaOrigemId }, data: { coberturaInicio: origem.coberturaOriginalInicio, coberturaFim: origem.coberturaOriginalFim } });
  const entrada = { matriculaId: origem.matriculaId, cobrancaId: origem.cobrancaOrigemId, versaoCobranca: origem.cobrancaVersao, dias: origem.diasPropostos, motivo: origem.motivo, evidenciaCondicoes: origem.evidenciaCondicoes, chaveIdempotencia: "compensacao-teste-1" };
  authMock.mockResolvedValue({ user: { id: origem.preparadorId } });
  const p = await prepararCompensacaoCobertura(entrada);
  expect(p.ok, p.ok ? undefined : p.erro).toBe(true); if (!p.ok || !p.dado) throw new Error("Proposta ausente");
  expect(await prepararCompensacaoCobertura(entrada)).toEqual(p);
  expect(await prisma.diaCompensacaoCobertura.count()).toBe(0);
  await prisma.usuario.update({ where: { id: origem.preparadorId }, data: { permissoes: ["financeiro.aprovar_acertos"] } });
  expect((await decidirCompensacaoCobertura({ id: p.dado.id, aprovar: true, motivo: "Autoaprovação indevida" })).ok).toBe(false);
  const financeiro = await criarUsuario(["FINANCEIRO"]);
  authMock.mockResolvedValue({ user: { id: financeiro.id } });
  expect((await decidirCompensacaoCobertura({ id: p.dado.id, aprovar: true, motivo: "Sem permissão específica" })).ok).toBe(false);
  await prisma.usuario.update({ where: { id: financeiro.id }, data: { permissoes: ["financeiro.aprovar_acertos"] } });
  const decisao = { id: p.dado.id, aprovar: true, motivo: "Conferência de origem e indisponibilidade" };
  const aprovado = await decidirCompensacaoCobertura(decisao);
  expect(aprovado.ok, aprovado.ok ? undefined : aprovado.erro).toBe(true);
  expect(await decidirCompensacaoCobertura(decisao)).toEqual(aprovado);
  expect(await prisma.diaCompensacaoCobertura.count()).toBe(2);
  const matricula = await prisma.matricula.findUniqueOrThrow({ where: { id: origem.matriculaId } });
  const direitos = await prisma.diaCompensacaoCobertura.findMany({ where: { matriculaId: origem.matriculaId } });
  const futura = await prisma.cobranca.create({ data: { matriculaId: matricula.id, tipo: "MENSALIDADE", moeda: "CRC", valorOriginal: 300, valorNegociado: 300, vencimento: new Date("2026-10-05"), coberturaInicio: new Date("2026-10-01"), coberturaFim: new Date("2026-10-31") } });
  const outra = await prisma.cobranca.create({ data: { matriculaId: outraMatriculaId, tipo: "MENSALIDADE", moeda: "CRC", valorOriginal: 700, valorNegociado: 700, vencimento: new Date("2026-10-10"), coberturaInicio: new Date("2026-10-01"), coberturaFim: new Date("2026-10-31") } });
  const recompor = { alunoId: matricula.alunoId, matriculaId: matricula.id, retornoOferta: "2026-10-01", inicioCompensacao: "2026-10-01", motivo: "Retorno da oferta confirmado", evidenciaCondicoes: "Condições conferidas do contrato", direitosIds: direitos.map((d) => d.id), periodosPropostos: [{ cobrancaId: origem.cobrancaOrigemId, cobertura: { inicio: "2026-09-01", fim: "2026-09-30" } }] };
  recompor.periodosPropostos.push({ cobrancaId: futura.id, cobertura: { inicio: "2026-10-03", fim: "2026-11-02" } });
  const sobreposta = await preverRecomposicaoCobertura({ ...recompor, periodosPropostos: recompor.periodosPropostos.map((p) => p.cobrancaId === futura.id ? { ...p, cobertura: { inicio: "2026-10-01", fim: "2026-10-31" } } : p) });
  expect(!sobreposta.ok && sobreposta.erro).toMatch(/sobrepostas/);
  const previa = await preverRecomposicaoCobertura(recompor);
  expect(previa.ok, previa.ok ? undefined : previa.erro).toBe(true);
  if (!previa.ok || !previa.dado) throw new Error("Prévia ausente");
  expect(previa.dado.proposta.compensacao).toEqual({ inicio: "2026-10-01", fim: "2026-10-02" });
  expect(previa.dado.efetivada).toBe(false);
  const salvar = { ...recompor, versaoAnterior: 0, chaveIdempotencia: "rascunho-recomposicao-teste" };
  const [r1, r2] = await Promise.all([salvarRascunhoRecomposicao(salvar), salvarRascunhoRecomposicao(salvar)]);
  expect(r1.ok, r1.ok ? undefined : r1.erro).toBe(true); expect(r2).toEqual(r1);
  if (!r1.ok || !r1.dado) throw new Error("Rascunho ausente");
  expect(await prisma.rascunhoRecomposicaoCobertura.count()).toBe(1);
  const conferir = { alunoId: matricula.alunoId, matriculaId: matricula.id, rascunhoId: r1.dado.id };
  const atual = await conferirValidadeRascunhoRecomposicao(conferir);
  expect(atual.ok && atual.dado?.atual).toBe(true);
  const documentoOutroContrato = await prisma.documento.create({ data: { matriculaId: outraMatriculaId, categoria: "CONTRATO", nome: "Contrato de outro serviço", url: "/api/files/outro-servico.pdf" } });
  await prisma.matricula.update({ where: { id: matricula.id }, data: { contratoDocumentoId: documentoOutroContrato.id } });
  expect((await preverRecomposicaoCobertura(recompor)).ok).toBe(false);
  const documentoIncompativel = await conferirValidadeRascunhoRecomposicao(conferir);
  expect(documentoIncompativel.ok && documentoIncompativel.dado?.atual).toBe(false);
  await prisma.matricula.update({ where: { id: matricula.id }, data: { contratoDocumentoId: doc.id } });
  await prisma.documento.update({ where: { id: doc.id }, data: { arquivado: true } });
  const arquivado = await conferirValidadeRascunhoRecomposicao(conferir);
  expect(arquivado.ok && arquivado.dado?.atual).toBe(false);
  await prisma.documento.update({ where: { id: doc.id }, data: { arquivado: false } });
  await prisma.cobranca.update({ where: { id: origem.cobrancaOrigemId }, data: { vencimento: new Date("2026-09-06") } });
  const mudou = await conferirValidadeRascunhoRecomposicao(conferir);
  expect(mudou.ok && mudou.dado?.atual).toBe(false);
  await prisma.cobranca.update({ where: { id: origem.cobrancaOrigemId }, data: { vencimento: new Date("2026-09-05") } });
  expect((await conferirValidadeRascunhoRecomposicao({ ...conferir, alunoId: "outra-pessoa" })).ok).toBe(false);
  expect((await salvarRascunhoRecomposicao({ ...salvar, motivo: "Mudança na mesma chave" })).ok).toBe(false);
  expect((await salvarRascunhoRecomposicao({ ...salvar, chaveIdempotencia: "outra-chave-recomposicao" })).ok).toBe(false);
  const revisado = await salvarRascunhoRecomposicao({ ...salvar, versaoAnterior: 1, chaveIdempotencia: "nova-versao-recomposicao", motivo: "Revisão da proposta preservando histórico" });
  expect(revisado.ok).toBe(true);
  const superado = await conferirValidadeRascunhoRecomposicao(conferir);
  expect(superado.ok && superado.dado?.atual).toBe(false);
  const historico = await consultarRascunhoRecomposicao({ alunoId: matricula.alunoId, matriculaId: matricula.id, versao: 1 });
  expect(historico.ok && historico.dado?.snapshot).toEqual(previa.dado);
  if (!revisado.ok || !revisado.dado) throw new Error("Revisão ausente");
  const decidir = { ...conferir, rascunhoId: revisado.dado.id, aprovar: true, motivo: "Recomposição conferida por outra pessoa" };
  expect((await decidirRecomposicaoCobertura(decidir)).ok).toBe(false);
  const semPermissao = await criarUsuario(["FINANCEIRO"]);
  authMock.mockResolvedValue({ user: { id: semPermissao.id } });
  expect((await decidirRecomposicaoCobertura(decidir)).ok).toBe(false);
  authMock.mockResolvedValue({ user: { id: decisorId } });
  expect((await decidirRecomposicaoCobertura({ ...decidir, rascunhoId: r1.dado.id })).ok).toBe(false);
  await prisma.cobranca.update({ where: { id: origem.cobrancaOrigemId }, data: { vencimento: new Date("2026-09-06") } });
  expect((await decidirRecomposicaoCobertura(decidir)).ok).toBe(false);
  await prisma.cobranca.update({ where: { id: origem.cobrancaOrigemId }, data: { vencimento: new Date("2026-09-05") } });
  const decisaoRecomposicao = await decidirRecomposicaoCobertura(decidir);
  expect(decisaoRecomposicao.ok).toBe(true);
  expect(await decidirRecomposicaoCobertura(decidir)).toEqual(decisaoRecomposicao);
  expect((await decidirRecomposicaoCobertura({ ...decidir, aprovar: false })).ok).toBe(false);
  expect(await prisma.decisaoRecomposicaoCobertura.count()).toBe(1);
  if (!decisaoRecomposicao.ok || !decisaoRecomposicao.dado) throw new Error("Decisão ausente");
  const aplicar = { alunoId: matricula.alunoId, matriculaId: matricula.id, decisaoId: decisaoRecomposicao.dado.id };
  expect((await aplicarRecomposicaoCobertura({ ...aplicar, alunoId: "outra-pessoa" })).ok).toBe(false);
  await prisma.cobranca.update({ where: { id: futura.id }, data: { valorNegociado: 301 } });
  expect((await aplicarRecomposicaoCobertura(aplicar)).ok).toBe(false);
  expect(await prisma.aplicacaoRecomposicaoCobertura.count()).toBe(0);
  expect(await prisma.diaProgramadoRecomposicao.count()).toBe(0);
  expect((await prisma.cobranca.findUniqueOrThrow({ where: { id: futura.id } })).coberturaInicio).toEqual(futura.coberturaInicio);
  await prisma.cobranca.update({ where: { id: futura.id }, data: { valorNegociado: 300 } });
  expect(await prisma.$transaction(async tx => (await import("./continuidade-recomposicao-tx")).carregarReferenciaRecomposicaoAplicadaTx(tx, matricula.id))).toBeNull();
  const aplicacao = await aplicarRecomposicaoCobertura(aplicar);
  expect(aplicacao.ok, aplicacao.ok ? undefined : aplicacao.erro).toBe(true);
  expect(await aplicarRecomposicaoCobertura(aplicar)).toEqual(aplicacao);
  expect(await prisma.diaProgramadoRecomposicao.count()).toBe(2);
  expect(await prisma.aplicacaoRecomposicaoCobertura.count()).toBe(1);
  const { carregarReferenciaRecomposicaoAplicadaTx } = await import("./continuidade-recomposicao-tx");
  const referenciaCiclo = await prisma.$transaction(tx => carregarReferenciaRecomposicaoAplicadaTx(tx, matricula.id));
  expect(referenciaCiclo).toMatchObject({ aplicacaoId: aplicacao.ok && aplicacao.dado?.id, decisaoId: decisaoRecomposicao.dado.id, cobrancaId: futura.id, dataReferencia: "2026-11-03" });
  expect(await prisma.$transaction(tx => carregarReferenciaRecomposicaoAplicadaTx(tx, outraMatriculaId))).toBeNull();
  const vencimentoPreservado = await prisma.cobranca.findUniqueOrThrow({ where: { id: futura.id } });
  expect(vencimentoPreservado.vencimento).toEqual(futura.vencimento);
  const { planejarContinuidadeMensalAposRecomposicao } = await import("./continuidade-mensal");
  const calculo = planejarContinuidadeMensalAposRecomposicao({
    continuidadeContratada: { contratada: true, clausula: "Continuidade prevista para teste de cálculo", evidenciaId: doc.id },
    regraCobertura: { referencia: "MES_CIVIL" }, ultimaCobertura: { inicio: "2026-10-03", fim: "2026-11-02" },
    referenciaVencimento: "MES_COBERTURA", diaVencimento: 5, antecedenciaDias: 10,
    valorOriginal: "300", valorNegociado: "300", moeda: "BRL", vigenteDesde: "2026-01-01",
    ajusteVencimento: "MANTER_DATA", dataPlanejamento: "2026-10-20",
  }, referenciaCiclo);
  expect(calculo).toMatchObject({ cobertura: { inicio: "2026-11-03", fim: "2026-12-02" }, vencimento: "2026-11-05", memoriaCobertura: { origemRecomposicao: referenciaCiclo } });

  const { conferirCompensacaoProgramadaContinuidadeTx } = await import("./continuidade-recomposicao-tx");
  const conferirNovaCobertura = (matriculaId: string, inicio: string, fim: string) => prisma.$transaction(tx =>
    conferirCompensacaoProgramadaContinuidadeTx(tx, { matriculaId, inicio: new Date(inicio), fim: new Date(fim) }));
  await expect(conferirNovaCobertura(matricula.id, "2026-10-01", "2026-10-31")).rejects.toThrow(/compens/i);
  await expect(conferirNovaCobertura(matricula.id, "2026-09-30", "2026-10-01")).rejects.toThrow(/compens/i);
  await expect(conferirNovaCobertura(matricula.id, "2026-10-02", "2026-10-02")).rejects.toThrow(/compens/i);
  await expect(conferirNovaCobertura(matricula.id, "2026-10-03", "2026-11-02")).resolves.toBeUndefined();
  await expect(conferirNovaCobertura(outraMatriculaId, "2026-10-01", "2026-10-31")).resolves.toBeUndefined();
  expect(await prisma.cobranca.findUniqueOrThrow({ where: { id: outra.id } })).toEqual(outra);
  await prisma.configuracaoOperacional.upsert({ where: { id: "escola" }, create: { id: "escola", fusoInstitucional: "America/Sao_Paulo" }, update: { fusoInstitucional: "America/Sao_Paulo" } });
  const programada = await prisma.diaProgramadoRecomposicao.findFirstOrThrow({ orderBy: { dataCobertura: "asc" } });
  const cumprimento = { alunoId: matricula.alunoId, matriculaId: matricula.id, programacaoId: programada.id, motivo: "Cobertura efetivamente disponibilizada", evidencia: "Conferência dos registros de oferta e vínculo", chaveIdempotencia: "cumprimento-teste-chave" };
  vi.useFakeTimers({ toFake: ["Date"] });
  try {
    vi.setSystemTime(new Date("2026-10-01T18:00:00Z"));
    expect((await prepararCumprimentoRecomposicao(cumprimento)).ok).toBe(false);
    vi.setSystemTime(new Date("2026-10-02T02:00:00Z"));
    expect((await prepararCumprimentoRecomposicao(cumprimento)).ok).toBe(false);
    vi.setSystemTime(new Date("2026-10-02T04:00:00Z"));
    const conferido = await prepararCumprimentoRecomposicao(cumprimento);
    expect(conferido.ok, conferido.ok ? undefined : conferido.erro).toBe(true);
    expect(await prepararCumprimentoRecomposicao(cumprimento)).toEqual(conferido);
    expect((await prepararCumprimentoRecomposicao({ ...cumprimento, chaveIdempotencia: "outra-chave-cumprimento" })).ok).toBe(false);
    expect((await prepararCumprimentoRecomposicao({ ...cumprimento, motivo: "Alteração de conteúdo na mesma chave" })).ok).toBe(false);
    expect(await prisma.conferenciaCumprimentoRecomposicao.count()).toBe(1);
    expect(await prisma.diaCompensacaoCobertura.count({ where: { estado: "PENDENTE" } })).toBe(2);
  } finally { vi.useRealTimers(); }
  await expect(prisma.aplicacaoRecomposicaoCobertura.updateMany({ data: { aplicadaEm: new Date("2020-01-01") } })).rejects.toThrow();
  await expect(prisma.diaProgramadoRecomposicao.updateMany({ data: { dataCobertura: new Date("2026-10-20") } })).rejects.toThrow();
  await expect(prisma.diaProgramadoRecomposicao.deleteMany()).rejects.toThrow();
  const deslocada = await prisma.cobranca.findUniqueOrThrow({ where: { id: futura.id } });
  expect(deslocada.coberturaInicio).toEqual(new Date("2026-10-03"));
  expect(deslocada.coberturaFim).toEqual(new Date("2026-11-02"));
  expect(deslocada.versao).toBe(futura.versao + 1);
  expect(deslocada.valorNegociado.equals(futura.valorNegociado)).toBe(true);
  expect(deslocada.vencimento).toEqual(futura.vencimento);
  expect(await prisma.cobranca.findUniqueOrThrow({ where: { id: outra.id } })).toEqual(outra);
  expect(await prisma.recebimento.count()).toBe(0);
  expect(await prisma.diaCompensacaoCobertura.count({ where: { estado: "PENDENTE" } })).toBe(2);
  await expect(prisma.decisaoRecomposicaoCobertura.updateMany({ data: { motivo: "Tentativa de editar decisão" } })).rejects.toThrow();
  await expect(prisma.rascunhoRecomposicaoCobertura.update({ where: { id: r1.dado.id }, data: { snapshot: {} } })).rejects.toThrow();
  await expect(prisma.rascunhoRecomposicaoCobertura.delete({ where: { id: r1.dado.id } })).rejects.toThrow();
  expect(await prisma.diaCompensacaoCobertura.count({ where: { estado: "PENDENTE" } })).toBe(2);
  expect((await preverRecomposicaoCobertura({ ...recompor, alunoId: "outra-pessoa" })).ok).toBe(false);
  expect((await preverRecomposicaoCobertura({ ...recompor, direitosIds: ["direito-inexistente"] })).ok).toBe(false);
  expect((await prisma.cobranca.findUniqueOrThrow({ where: { id: origem.cobrancaOrigemId } })).valorNegociado.toFixed(2)).toBe("300.00");
  authMock.mockResolvedValue({ user: { id: origem.preparadorId } });
  expect((await prepararCompensacaoCobertura({ ...entrada, chaveIdempotencia: "compensacao-repetida" })).ok).toBe(false);
  const nova = await prepararCompensacaoCobertura({ ...entrada, dias: ["2026-09-12"], chaveIdempotencia: "compensacao-teste-2" });
  expect(nova.ok).toBe(true); if (!nova.ok || !nova.dado) throw new Error("Proposta ausente");
  await prisma.cobranca.update({ where: { id: origem.cobrancaOrigemId }, data: { versao: { increment: 1 } } });
  authMock.mockResolvedValue({ user: { id: decisorId } });
  expect((await decidirCompensacaoCobertura({ id: nova.dado.id, aprovar: true, motivo: "Conferência desatualizada" })).ok).toBe(false);
  expect((await decidirCompensacaoCobertura({ id: nova.dado.id, aprovar: false, motivo: "Rejeitar origem desatualizada" })).ok).toBe(true);
  expect(await prisma.diaCompensacaoCobertura.count()).toBe(2);
  const extra = await prisma.compensacaoCoberturaMatricula.create({ data: { ...origem, diasPropostos: ["2026-09-13"], status: "APROVADA", decisorId, decididaEm: new Date(), motivoDecisao: "Outro dia de indisponibilidade reconhecido" } });
  const direitoExtra = await prisma.diaCompensacaoCobertura.create({ data: { compensacaoId: extra.id, matriculaId: matricula.id, diaOrigem: new Date("2026-09-13") } });
  if (!aplicacao.ok || !aplicacao.dado) throw new Error("Aplicação ausente");
  await expect(prisma.diaProgramadoRecomposicao.create({ data: { aplicacaoId: aplicacao.dado.id, direitoId: direitos[0].id, dataCobertura: new Date("2026-12-25") } })).rejects.toThrow(/corresponder exatamente/);
  await expect(prisma.diaProgramadoRecomposicao.create({ data: { aplicacaoId: aplicacao.dado.id, direitoId: direitoExtra.id, dataCobertura: new Date("2026-11-03") } })).rejects.toThrow();
  const rejeitada = await prisma.decisaoRecomposicaoCobertura.create({ data: { rascunhoId: r1.dado.id, decisorId, aprovada: false, motivo: "Versão antiga rejeitada" } });
  await expect(prisma.aplicacaoRecomposicaoCobertura.create({ data: { decisaoId: rejeitada.id, executorId: decisorId } })).rejects.toThrow(/decisão aprovada/);
  const outraProposta = { ...recompor, direitosIds: [direitoExtra.id] };
  const conflitoProgramacao = await preverRecomposicaoCobertura(outraProposta);
  expect(!conflitoProgramacao.ok && conflitoProgramacao.erro).toMatch(/já programado/);
  const depois = { ...outraProposta, inicioCompensacao: "2026-11-03" };
  expect((await preverRecomposicaoCobertura(depois)).ok).toBe(true);
  const ocupandoDia = await preverRecomposicaoCobertura({ ...depois, periodosPropostos: depois.periodosPropostos.map((p) => p.cobrancaId === futura.id ? { ...p, cobertura: { inicio: "2026-10-02", fim: "2026-11-01" } } : p) });
  expect(!ocupandoDia.ok && ocupandoDia.erro).toMatch(/já programado/);
  expect(await prisma.diaProgramadoRecomposicao.count()).toBe(2);
  const conferencia = await prisma.conferenciaCumprimentoRecomposicao.findFirstOrThrow();
  const decidirCumprimento = { alunoId: matricula.alunoId, matriculaId: matricula.id, conferenciaId: conferencia.id,
    aprovar: true, motivo: "Evidência de oferta efetiva conferida", evidenciaConferida: true };
  vi.useFakeTimers({ toFake: ["Date"] });
  try {
    vi.setSystemTime(new Date("2026-10-02T04:00:00Z"));
    authMock.mockResolvedValue({ user: { id: conferencia.preparadorId } });
    expect((await decidirCumprimentoRecomposicao(decidirCumprimento)).ok).toBe(false);
    authMock.mockResolvedValue({ user: { id: financeiro.id } });
    await prisma.usuario.update({ where: { id: financeiro.id }, data: { permissoes: [] } });
    expect((await decidirCumprimentoRecomposicao(decidirCumprimento)).ok).toBe(false);
    await prisma.usuario.update({ where: { id: financeiro.id }, data: { permissoes: ["financeiro.aprovar_acertos"] } });
    expect((await decidirCumprimentoRecomposicao({ ...decidirCumprimento, evidenciaConferida: false })).ok).toBe(false);
    expect((await decidirCumprimentoRecomposicao({ ...decidirCumprimento, alunoId: "outro-aluno" })).ok).toBe(false);
    const semHistorico = await decidirCumprimentoRecomposicao(decidirCumprimento);
    expect(!semHistorico.ok && semHistorico.erro).toMatch(/histórica/);
    const rejeicao = { ...decidirCumprimento, aprovar: false, evidenciaConferida: false, motivo: "Histórico precisa ser conferido" };
    const rejeitado = await decidirCumprimentoRecomposicao(rejeicao);
    expect(rejeitado.ok).toBe(true);
    expect(await decidirCumprimentoRecomposicao(rejeicao)).toEqual(rejeitado);
    expect((await prisma.diaCompensacaoCobertura.findUniqueOrThrow({ where: { id: programada.direitoId } })).estado).toBe("PENDENTE");
    await expect(prisma.conferenciaCumprimentoRecomposicao.update({ where: { id: conferencia.id }, data: { evidencia: "Evidência alterada posteriormente" } })).rejects.toThrow();
    await expect(prisma.conferenciaCumprimentoRecomposicao.delete({ where: { id: conferencia.id } })).rejects.toThrow();
    authMock.mockResolvedValue({ user: { id: conferencia.preparadorId } });
    const novaConferencia = await prepararCumprimentoRecomposicao({ ...cumprimento, chaveIdempotencia: "cumprimento-nova-conferencia" });
    if (!novaConferencia.ok || !novaConferencia.dado) throw new Error("Nova conferência ausente");
    const novaDecisao = { ...decidirCumprimento, conferenciaId: novaConferencia.dado.id };
    await prisma.matricula.update({ where: { id: matricula.id }, data: { ativadaEm: new Date("2026-09-01"), status: "ATIVA" } });
    authMock.mockResolvedValue({ user: { id: financeiro.id } });
    await prisma.configuracaoOperacional.update({ where: { id: "escola" }, data: { fusoInstitucional: "UTC" } });
    expect((await decidirCumprimentoRecomposicao(novaDecisao)).ok).toBe(false);
    await prisma.configuracaoOperacional.update({ where: { id: "escola" }, data: { fusoInstitucional: "America/Sao_Paulo" } });
    const cumprido = await decidirCumprimentoRecomposicao(novaDecisao);
    expect(cumprido.ok, cumprido.ok ? undefined : cumprido.erro).toBe(true);
    expect(await decidirCumprimentoRecomposicao(novaDecisao)).toEqual(cumprido);
    const direitoCumprido = await prisma.diaCompensacaoCobertura.findUniqueOrThrow({ where: { id: programada.direitoId } });
    expect(direitoCumprido.estado).toBe("RECOMPOSTO");
    expect(direitoCumprido.destinacaoReferencia).toBe(novaConferencia.dado.id);
    expect(direitoCumprido.versao).toBe(2);
    expect(await prisma.diaCompensacaoCobertura.count({ where: { estado: "RECOMPOSTO" } })).toBe(1);
    expect(await prisma.recebimento.count()).toBe(0);
    const consulta = await consultarCumprimentosRecomposicao({ alunoId: matricula.alunoId, matriculaId: matricula.id });
    expect(consulta.ok).toBe(true);
    if (!consulta.ok || !consulta.dado) throw new Error("Consulta ausente");
    expect(consulta.dado).toHaveLength(2);
    expect(consulta.dado[0].estado).toBe("RECOMPOSTO");
    expect(consulta.dado[0].conferencias.map((c) => c.status).sort()).toEqual(["APROVADA", "REJEITADA"]);
    expect(consulta.dado[0].conferencias.every((c) => c.preparador.nome && c.decisor?.nome && c.evidencia)).toBe(true);
    expect((await consultarCumprimentosRecomposicao({ alunoId: "outro-aluno", matriculaId: matricula.id })).ok).toBe(false);
    expect(await consultarCumprimentosRecomposicao({ alunoId: matricula.alunoId, matriculaId: outraMatriculaId })).toMatchObject({ ok: true, dado: [] });
    const professor = await criarUsuario(["PROFESSOR"]);
    authMock.mockResolvedValue({ user: { id: professor.id } });
    expect((await consultarCumprimentosRecomposicao({ alunoId: matricula.alunoId, matriculaId: matricula.id })).ok).toBe(false);
  } finally { vi.useRealTimers(); }
});
import { preverRecomposicaoCobertura } from "./recomposicao-previa";
import { salvarRascunhoRecomposicao, consultarRascunhoRecomposicao } from "./recomposicao-rascunho";
import { conferirValidadeRascunhoRecomposicao } from "./recomposicao-validade";
import { decidirRecomposicaoCobertura } from "./recomposicao-decisao";
import { aplicarRecomposicaoCobertura } from "./recomposicao-aplicar";
import { prepararCumprimentoRecomposicao, decidirCumprimentoRecomposicao, consultarCumprimentosRecomposicao } from "./recomposicao-cumprimento";
