import { beforeEach, describe, expect, it, vi } from "vitest";
const h=vi.hoisted(()=>({auth:vi.fn(),tx:{usuario:{findUnique:vi.fn()},pedidoDesistenciaPreparacao:{findUnique:vi.fn(),findFirst:vi.fn()},matricula:{findUniqueOrThrow:vi.fn()},efetivacaoPedidoDesistenciaPreparacao:{findFirst:vi.fn()},condicoesEncerramentoMatricula:{findFirst:vi.fn()},propostaAcertoDesistenciaContratual:{create:vi.fn(),findUnique:vi.fn()}}}));
vi.mock("@/lib/auth",()=>({auth:h.auth}));
vi.mock("@/lib/prisma",()=>({prisma:{$transaction:(f:any)=>f(h.tx)}}));
vi.mock("@/server/financeiro/recebimentos",()=>({bloquearMatriculas:vi.fn()}));
import { prepararAcertoDesistenciaContratual } from "./desistencia-acerto-contratual";
describe("prepararAcertoDesistenciaContratual",()=>{ beforeEach(()=>{vi.clearAllMocks();});it("recusa matrícula ativa antes de criar proposta",async()=>{h.auth.mockResolvedValue({user:{id:"fin"}});h.tx.usuario.findUnique.mockResolvedValue({ativo:true,papeis:["FINANCEIRO"]});h.tx.pedidoDesistenciaPreparacao.findUnique.mockResolvedValue({id:"p",matriculaId:"m"});h.tx.pedidoDesistenciaPreparacao.findFirst.mockResolvedValue({id:"p"});h.tx.efetivacaoPedidoDesistenciaPreparacao.findFirst.mockResolvedValue(null);h.tx.matricula.findUniqueOrThrow.mockResolvedValue({status:"ATIVA",ativadaEm:new Date(),contratoOk:true,contratoDocumentoId:"d",confirmacaoContratoEm:new Date(),confirmacaoContratoPorId:"s"});const r=await prepararAcertoDesistenciaContratual({pedidoId:"p",condicoesId:"c",motivo:"Motivo válido",chaveIdempotencia:"chave-123"});expect(r.ok).toBe(false);expect(h.tx.propostaAcertoDesistenciaContratual.create).not.toHaveBeenCalled();}); it.each(["documento não aceito","pedido antigo"])("recusa %s sem criar proposta",async tipo=>{ h.auth.mockResolvedValue({user:{id:"fin"}});h.tx.usuario.findUnique.mockResolvedValue({ativo:true,papeis:["FINANCEIRO"]});h.tx.pedidoDesistenciaPreparacao.findUnique.mockResolvedValue({id:"p",matriculaId:"m"});h.tx.pedidoDesistenciaPreparacao.findFirst.mockResolvedValue({id:tipo==="pedido antigo"?"novo":"p"});h.tx.efetivacaoPedidoDesistenciaPreparacao.findFirst.mockResolvedValue(null);h.tx.matricula.findUniqueOrThrow.mockResolvedValue({status:"RASCUNHO",ativadaEm:null,contratoOk:true,contratoDocumentoId:"d",confirmacaoContratoEm:new Date(),confirmacaoContratoPorId:"s"});h.tx.condicoesEncerramentoMatricula.findFirst.mockResolvedValue(tipo==="documento não aceito"?null:undefined);const r=await prepararAcertoDesistenciaContratual({pedidoId:"p",condicoesId:"c",motivo:"Motivo válido",chaveIdempotencia:"chave-456"});expect(r.ok).toBe(false);expect(h.tx.propostaAcertoDesistenciaContratual.create).not.toHaveBeenCalled();});});

// A fotografia é comparada como hash do estado financeiro inteiro; este caso
// puro documenta o gatilho que a ação usa antes de gravar uma decisão.
it("detecta fotografia financeira alterada", async () => {
  const { hashSubstituicao } = await import("@/server/contratos/substituicao-estado");
  const antes = { cobrancas: [{ id: "c", versao: 1, valorNegociado: "100.00", valorRecebido: null, valorLiquidadoCredito: "0.00", valorCompensadoPermuta: "0.00" }] };
  const depois = { cobrancas: [{ id: "c", versao: 1, valorNegociado: "100.00", valorRecebido: "30.00", valorLiquidadoCredito: "0.00", valorCompensadoPermuta: "0.00" }] };
  expect(hashSubstituicao(depois)).not.toBe(hashSubstituicao(antes));
});
