"use server";
import { Papel, Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { executarAcao, exigirSessaoComPapel, ErroPermissao, ErroRegra, registrarEvento } from "@/server/_shared";
import { bloquearMatriculas } from "@/server/financeiro/recebimentos";
import { calcularObrigacaoDesistenciaContratual } from "./desistencia-acerto-contratual-calculo";
import { carregarFinanceiroDesistenciaTx } from "./desistencia-financeiro-tx";
import { hashSubstituicao } from "@/server/contratos/substituicao-estado";
import { conferirPedidoReplayAcertoDesistencia } from "./desistencia-acerto-replay";
const id=z.string().min(1).max(100), motivo=z.string().trim().min(5).max(3000);
const Entrada=z.object({pedidoId:id,condicoesId:id,motivo,chaveIdempotencia:z.string().trim().min(8).max(100)}).strict();
async function fotografiaQ165(tx: Prisma.TransactionClient, matriculaId: string) { const [taxa, desist] = await Promise.all([tx.origemCreditoAcertoTaxaAditivo.findMany({ where: { cobranca: { matriculaId } }, select: { cobrancaId: true, valor: true } }), tx.origemCreditoAcertoDesistenciaContratual.findMany({ where: { matriculaId }, select: { cobrancaId: true, valor: true } })]); const credito = new Map<string, Prisma.Decimal>(); for (const x of [...taxa, ...desist]) credito.set(x.cobrancaId, (credito.get(x.cobrancaId) ?? new Prisma.Decimal(0)).plus(x.valor)); const financeiro = await carregarFinanceiroDesistenciaTx(tx, matriculaId); return { fotografia: { financeiro: financeiro.snapshot, creditoJaApurado: Object.fromEntries([...credito].map(([c,v])=>[c,v.toFixed(2)])) }, credito }; }
async function autor(tx:Prisma.TransactionClient, uid:string){const u=await tx.usuario.findUnique({where:{id:uid},select:{ativo:true,papeis:true}});if(!u?.ativo||!u.papeis.some(p=>p===Papel.FINANCEIRO||p===Papel.ADMINISTRADOR))throw new ErroPermissao();}
export async function prepararAcertoDesistenciaContratual(input:unknown){return executarAcao(async()=>{const a=await exigirSessaoComPapel(Papel.FINANCEIRO,Papel.ADMINISTRADOR),d=Entrada.parse(input);return prisma.$transaction(async tx=>{await autor(tx,a.id);const pedido=await tx.pedidoDesistenciaPreparacao.findUnique({where:{id:d.pedidoId}});if(!pedido)throw new ErroRegra("Pedido de desistência indisponível.");await bloquearMatriculas(tx,[pedido.matriculaId]);const replay=await tx.propostaAcertoDesistenciaContratual.findUnique({where:{preparadorId_chaveIdempotencia:{preparadorId:a.id,chaveIdempotencia:d.chaveIdempotencia}}});if(replay){conferirPedidoReplayAcertoDesistencia(replay,d);return {id:replay.id};}const matricula = await tx.matricula.findUniqueOrThrow({ where: { id: pedido.matriculaId }, select: { status: true, ativadaEm: true, contratoOk: true, contratoDocumentoId: true, confirmacaoContratoEm: true, confirmacaoContratoPorId: true } }); if(matricula.ativadaEm || !["RASCUNHO","AGUARDANDO"].includes(matricula.status))throw new ErroRegra("O acerto contratual exige matrícula em preparação.");const atualPedido = await tx.pedidoDesistenciaPreparacao.findFirst({ where: { matriculaId: pedido.matriculaId }, orderBy: { versao: "desc" } }); if (!atualPedido || atualPedido.id !== pedido.id || await tx.efetivacaoPedidoDesistenciaPreparacao.findFirst({ where: { matriculaId: pedido.matriculaId } })) throw new ErroRegra("Use o pedido atual ainda não efetivado."); const c=await tx.condicoesEncerramentoMatricula.findFirst({where:{id:d.condicoesId,matriculaId:pedido.matriculaId,status:"APROVADA"},include:{documento:true,artefatoContratual:{include:{previa:true}},processoAssinatura:{include:{conclusao:true}}}});const fonteDocumento=!!c?.documento&&!!matricula.contratoOk&&!!matricula.confirmacaoContratoEm&&!!matricula.confirmacaoContratoPorId&&c.documentoId===matricula.contratoDocumentoId&&!c.documento.arquivado&&c.documento.matriculaId===pedido.matriculaId;const fonteEnviada=!!c?.artefatoContratual&&!!c.processoAssinatura&&!c.documentoId&&c.artefatoContratual.previa.matriculaId===pedido.matriculaId&&c.processoAssinatura.matriculaId===pedido.matriculaId&&c.processoAssinatura.artefatoId===c.artefatoContratualId&&c.processoAssinatura.estado==="ENVIADO"&&!!c.processoAssinatura.referenciaExterna&&!c.processoAssinatura.conclusao&&!!(c.regras as any).acertoDesistenciaPreparacao;if(!c||(!fonteDocumento&&!fonteEnviada)||await tx.condicoesEncerramentoMatricula.count({where:{matriculaId:pedido.matriculaId,versao:{gt:c.versao}}}))throw new ErroRegra("Use a versão contratual estruturada vigente e aprovada.");const { fotografia, credito: creditoJaApurado } = await fotografiaQ165(tx, pedido.matriculaId);
if(await tx.aplicacaoAcertoDesistenciaContratual.findFirst({where:{decisao:{proposta:{pedidoId:pedido.id}}},select:{id:true}}))throw new ErroRegra("Este pedido já possui aplicação Q165 pendente de efetivação.");const cobrancas=await tx.cobranca.findMany({where:{matriculaId:pedido.matriculaId},orderBy:{id:"asc"}});const itens=cobrancas.map(x=>{const r=calcularObrigacaoDesistenciaContratual(c.regras,{...x,valorCreditoJaApurado:creditoJaApurado.get(x.id) ?? new Prisma.Decimal(0)},cobrancas);return {cobrancaId:x.id,moeda:x.moeda,devido:r.devido.toFixed(2),saldoDevido:r.saldoDevido.toFixed(2),creditoApurado:r.creditoApurado.toFixed(2),creditoJaApurado:(creditoJaApurado.get(x.id) ?? new Prisma.Decimal(0)).toFixed(2)};});const fotografiaHash=hashSubstituicao(fotografia);const memoria={pedidoId:pedido.id,matriculaId:pedido.matriculaId,condicoesId:c.id,estadoHash:pedido.estadoHash,condicoesHash:hashSubstituicao(c.regras),fotografiaHash,fotografia,regras:c.regras,itens,motivo:d.motivo};const p=await tx.propostaAcertoDesistenciaContratual.create({data:{pedidoId:pedido.id,condicoesId:c.id,preparadorId:a.id,estadoHash:pedido.estadoHash,condicoesHash:hashSubstituicao(c.regras),fotografiaHash,memoria,chaveIdempotencia:d.chaveIdempotencia}});await registrarEvento(tx,{tipo:"AcertoDesistenciaContratualPreparado",agregadoTipo:"Matricula",agregadoId:pedido.matriculaId,autorId:a.id,payload:{propostaId:p.id,pedidoId:pedido.id,fotografiaHash}});return {id:p.id};});});}

export async function decidirAcertoDesistenciaContratual(input: unknown) { return executarAcao(async () => {
  const ator = await exigirSessaoComPapel(Papel.FINANCEIRO, Papel.ADMINISTRADOR);
  const d = z.object({ propostaId: id, fotografiaHash: z.string().regex(/^[a-f0-9]{64}$/), aprovada: z.boolean(), motivo, chaveIdempotencia: z.string().trim().min(8).max(100) }).strict().parse(input);
  return prisma.$transaction(async tx => {
    const referencia = await tx.propostaAcertoDesistenciaContratual.findUniqueOrThrow({ where: { id: d.propostaId }, select: { pedido: { select: { matriculaId: true } } } });
    await bloquearMatriculas(tx, [referencia.pedido.matriculaId]);
    const proposta = await tx.propostaAcertoDesistenciaContratual.findUniqueOrThrow({ where: { id: d.propostaId }, include: { pedido: true, decisao: true } });
    const u = await tx.usuario.findUnique({ where: { id: ator.id }, select: { ativo: true, papeis: true, permissoes: true } });
    if (!u?.ativo || (!u.papeis.includes(Papel.ADMINISTRADOR) && (!u.papeis.includes(Papel.FINANCEIRO) || !u.permissoes.includes("financeiro.aprovar_acertos")))) throw new ErroPermissao();
    if (proposta.preparadorId === ator.id || proposta.fotografiaHash !== d.fotografiaHash) throw new ErroRegra("Decisão não corresponde à proposta independente.");
    if (proposta.decisao) { if (proposta.decisao.decisorId !== ator.id || proposta.decisao.aprovada !== d.aprovada || proposta.decisao.motivo !== d.motivo || proposta.decisao.chaveIdempotencia !== d.chaveIdempotencia) throw new ErroRegra("Proposta já decidida com outros dados."); return { id: proposta.decisao.id, aprovada: proposta.decisao.aprovada }; }
    if (d.aprovada) { if(await tx.condicoesEncerramentoMatricula.count({where:{matriculaId:proposta.pedido.matriculaId,versao:{gt:(await tx.condicoesEncerramentoMatricula.findUniqueOrThrow({where:{id:proposta.condicoesId},select:{versao:true}})).versao}}}))throw new ErroRegra("A versão contratual mudou; prepare novo acerto."); const { fotografia: fotografiaAtual } = await fotografiaQ165(tx, proposta.pedido.matriculaId); if (hashSubstituicao(fotografiaAtual) !== proposta.fotografiaHash) throw new ErroRegra("A fotografia financeira mudou; prepare novo acerto."); }
    const decisao = await tx.decisaoAcertoDesistenciaContratual.create({ data: { propostaId: proposta.id, decisorId: ator.id, aprovada: d.aprovada, motivo: d.motivo, condicoesHash: proposta.condicoesHash, fotografiaHash: proposta.fotografiaHash, chaveIdempotencia: d.chaveIdempotencia } });
    await registrarEvento(tx, { tipo: "AcertoDesistenciaContratualDecidido", agregadoTipo: "Matricula", agregadoId: proposta.pedido.matriculaId, autorId: ator.id, payload: { propostaId: proposta.id, decisaoId: decisao.id, aprovada: d.aprovada, fotografiaHash: proposta.fotografiaHash } });
    return { id: decisao.id, aprovada: decisao.aprovada };
  });
}); }
