import { consultarJanelasAdmissao } from "./janela-admissao-consulta";
import { beforeEach, expect, it, vi } from "vitest";
const { authMock } = vi.hoisted(() => ({ authMock: vi.fn() }));
vi.mock("@/lib/auth", () => ({ auth: authMock }));
import { prisma } from "@/lib/prisma";
import { criarUsuario, seedCatalogoMinimo, truncarBanco } from "@/test/integracao";
import { prepararJanelaAdmissao, decidirJanelaAdmissao } from "./janela-admissao";
import { carregarJanelaAdmissaoVigente } from "./janela-admissao-tx";
let turmaId: string, autorId: string, gestorId: string;
beforeEach(async () => {
  await truncarBanco(); await seedCatalogoMinimo();
  const autor = await criarUsuario(["SECRETARIA_ACADEMICA", "GERENTE_PEDAGOGICO"]), gestor = await criarUsuario(["GERENTE_PEDAGOGICO"]);
  autorId = autor.id; gestorId = gestor.id; authMock.mockResolvedValue({ user: { id: autorId } });
  const modalidade = await prisma.modalidade.findFirstOrThrow(), idioma = await prisma.idioma.findFirstOrThrow();
  const nivel = await prisma.nivel.create({ data: { idiomaId: idioma.id, codigo: "JANELA", ordem: 1 } });
  turmaId = (await prisma.turma.create({ data: { modalidadeId: modalidade.id, nivelId: nivel.id } })).id;
  await prisma.configuracaoOperacional.upsert({ where: { id: "escola" }, create: { id: "escola", fusoInstitucional: "UTC" }, update: { fusoInstitucional: "UTC" } });
});
const entrada = () => ({ turmaId, limiteEntrada: "2099-10-20", fusoConferido: "UTC", versaoAnterior: 0, motivo: "Janela de entrada conferida", chaveIdempotencia: "janela-primeira" });
it("preserva versões, exige decisão independente e torna vigente apenas aprovação", async () => {
  const p = await prepararJanelaAdmissao(entrada());
  if (!p.ok || !p.dado) throw new Error("Proposta ausente");
  expect(await prepararJanelaAdmissao(entrada())).toEqual(p);
  expect(await carregarJanelaAdmissaoVigente(prisma, turmaId)).toBeNull();
  expect(await consultarJanelasAdmissao({ turmaId })).toMatchObject({ ok: true, dado: { vigente: null, ultimaVersao: 1, registros: [{ podeDecidir: false }] } });
  const d = { propostaId: p.dado.id, aprovar: true, motivo: "Conferência pedagógica independente" };
  expect((await decidirJanelaAdmissao(d)).ok).toBe(false);
  await expect(prisma.decisaoJanelaAdmissao.create({ data: { propostaId: p.dado.id, decisorId: autorId, aprovada: true, motivo: "Autoaprovação por SQL" } })).rejects.toThrow();
  authMock.mockResolvedValue({ user: { id: gestorId } });
  expect(await consultarJanelasAdmissao({ turmaId })).toMatchObject({ ok: true, dado: { registros: [{ podeDecidir: true, podeAprovar: true }] } });
  expect(await consultarJanelasAdmissao({ turmaId, pagina: 2 })).toMatchObject({ ok: true, dado: { registros: [], possuiMais: false } });
  const decisao = await decidirJanelaAdmissao(d); expect(decisao.ok).toBe(true); expect(await decidirJanelaAdmissao(d)).toEqual(decisao);
  expect(await carregarJanelaAdmissaoVigente(prisma, turmaId)).toMatchObject({ versao: 1, limiteEntrada: "2099-10-20", fusoAdmissao: "UTC" });
  await expect(prisma.janelaAdmissaoTurma.updateMany({ data: { motivo: "Reescrever histórico" } })).rejects.toThrow();
  await expect(prisma.decisaoJanelaAdmissao.deleteMany()).rejects.toThrow();
  authMock.mockResolvedValue({ user: { id: autorId } });
  const segunda = await prepararJanelaAdmissao({ ...entrada(), versaoAnterior: 1, limiteEntrada: "2099-10-21", chaveIdempotencia: "janela-segunda" });
  if (!segunda.ok || !segunda.dado) throw new Error("Segunda ausente");
  expect((await carregarJanelaAdmissaoVigente(prisma, turmaId))?.versao).toBe(1);
  authMock.mockResolvedValue({ user: { id: gestorId } });
  expect((await decidirJanelaAdmissao({ ...d, propostaId: segunda.dado.id, aprovar: false })).ok).toBe(true);
  expect((await carregarJanelaAdmissaoVigente(prisma, turmaId))?.versao).toBe(1);
  expect(await prisma.matricula.count()).toBe(0); expect(await prisma.encontroAgenda.count()).toBe(0);
});
it("recusa versão superada, fuso alterado e turma concluída", async () => {
  const p = await prepararJanelaAdmissao(entrada()); if (!p.ok || !p.dado) throw new Error("Ausente");
  expect((await prepararJanelaAdmissao({ ...entrada(), chaveIdempotencia: "outra-chave" })).ok).toBe(false);
  const p2 = await prepararJanelaAdmissao({ ...entrada(), versaoAnterior: 1, chaveIdempotencia: "outra-versao" }); if (!p2.ok || !p2.dado) throw new Error("Ausente");
  authMock.mockResolvedValue({ user: { id: gestorId } });
  const d = { aprovar: true, motivo: "Decisão conferida pela gestão" };
  expect((await decidirJanelaAdmissao({ ...d, propostaId: p.dado.id })).ok).toBe(false);
  await prisma.configuracaoOperacional.update({ where: { id: "escola" }, data: { fusoInstitucional: "America/Sao_Paulo" } });
  expect((await decidirJanelaAdmissao({ ...d, propostaId: p2.dado.id })).ok).toBe(false);
  await prisma.turma.update({ where: { id: turmaId }, data: { status: "CONCLUIDA" } });
  expect((await prepararJanelaAdmissao({ ...entrada(), versaoAnterior: 2, fusoConferido: "America/Sao_Paulo", chaveIdempotencia: "concluida-chave" })).ok).toBe(false);
  expect((await decidirJanelaAdmissao({ ...d, propostaId: p2.dado.id })).ok).toBe(false);
});
it("nega preparação e decisão a professor sem papel autorizado", async () => {
  const p = await prepararJanelaAdmissao(entrada()); if (!p.ok || !p.dado) throw new Error("Ausente");
  const professor = await criarUsuario(["PROFESSOR"]); authMock.mockResolvedValue({ user: { id: professor.id } });
  expect((await consultarJanelasAdmissao({ turmaId })).ok).toBe(false);
  expect((await prepararJanelaAdmissao(entrada())).ok).toBe(false);
  expect((await decidirJanelaAdmissao({ propostaId: p.dado.id, aprovar: true, motivo: "Tentativa sem permissão" })).ok).toBe(false);
});
