import Link from "next/link";
import { Papel } from "@prisma/client";
import { exigirSessaoPagina } from "@/server/_shared";
import { consultarLotePreparacaoMigracao } from "@/server/migracao/consultas";

export default async function LotePreparacaoPage({ params }: { params: Promise<{ loteId: string }> }) {
  await exigirSessaoPagina(Papel.ADMINISTRADOR); const { loteId } = await params; const resultado = await consultarLotePreparacaoMigracao(loteId); const lote = resultado.ok ? resultado.dado : null;
  if (!lote) return <section className="space-y-3"><Link href="/configuracao/migracao" className="text-sm text-brand-700 underline">Voltar aos lotes</Link><p className="text-sm text-red-700">{resultado.ok ? "Lote não encontrado." : resultado.erro}</p></section>;
  return <section className="max-w-5xl space-y-5"><Link href="/configuracao/migracao" className="text-sm text-brand-700 underline">Voltar aos lotes</Link><div><h2 className="text-lg font-medium">{lote.origem} · {lote.chaveLote}</h2><p className="text-sm text-gray-600">Preparado por {lote.preparadoPor.nome}. Estado: {lote.estado === "PREPARADO" ? "Preparado" : "Com pendências"}. A fonte permanece uma prévia; não há aplicação nesta tela.</p></div>{lote.conflitosEntrada.length > 0 && <div className="rounded border border-amber-300 bg-amber-50 p-3 text-sm"><strong>Tentativas divergentes preservadas</strong><ul className="mt-2 space-y-3">{lote.conflitosEntrada.map((conflito, i) => <li key={`${conflito.linhaOrigem}-${i}`}><p>Linha {conflito.linhaOrigem}: {conflito.codigo} · hash {conflito.entradaHash} · {conflito.registradoPorNome ?? "autoria anterior indisponível"} em {conflito.registradoEm.toLocaleString("pt-BR")}</p><pre className="mt-1 overflow-auto rounded bg-white p-2 text-xs">{JSON.stringify(conflito.dadosConflitantes, null, 2)}</pre></li>)}</ul></div>}<ul className="space-y-3">{lote.linhas.map((linha) => <li key={linha.id} className="rounded border p-4 text-sm"><div className="flex justify-between gap-3"><strong>Linha {linha.linhaOrigem}</strong><span>{linha.estado}</span></div><p className="mt-1 text-gray-600">Aluno: {linha.alunoOrigemId ?? "não identificado"} · Turma: {linha.turmaOrigemId ?? "não identificada"} · Matrícula: {linha.matriculaOrigemId ?? "não identificada"} · Financeiro: {linha.financeiroOrigemId ?? "não identificado"}</p><p className="mt-2 text-xs text-gray-500">Fotografia de origem · hash {linha.entradaHash}</p><pre className="mt-1 overflow-auto rounded bg-gray-50 p-2 text-xs">{JSON.stringify(linha.dadosOrigem, null, 2)}</pre>{linha.pendencias.length > 0 && <ul className="mt-2 list-disc pl-5 text-amber-800">{linha.pendencias.map((pendencia) => <li key={`${pendencia.campo}-${pendencia.codigo}`}><code>{pendencia.campo}</code>: {pendencia.detalhe}</li>)}</ul>}{linha.colisoes.length > 0 && <ul className="mt-2 list-disc pl-5 text-red-700">{linha.colisoes.map((colisao, i) => <li key={`${colisao.tipo}-${i}`}>Identificador {colisao.identificadorOrigem} em conflito com a linha {colisao.outraLinhaOrigem}.</li>)}</ul>}</li>)}</ul></section>;
}
