-- Corretiva 189. CREATE OR REPLACE preserva o OID dos gatilhos consumidores.
CREATE OR REPLACE FUNCTION situacao_autorizacao_segunda_chamada_cobre_intervalo(matricula_id TEXT,alocacao_id TEXT,codigo_avaliacao TEXT,inicio TIMESTAMP,fim TIMESTAMP)
RETURNS BOOLEAN LANGUAGE plpgsql VOLATILE AS $$
DECLARE ativada_em TIMESTAMP; limite_vinculo TIMESTAMP; alocacao_ativa BOOLEAN; proveniencia "ProvenienciaVinculoMatricula"; inicio_vigencia TIMESTAMP; fim_vigencia TIMESTAMP; encerrada_em TIMESTAMP; criada_em TIMESTAMP; inicio_alocacao TIMESTAMP; ha_fatos BOOLEAN; ponto RECORD; situacao TEXT;
BEGIN
 IF matricula_id IS NULL OR alocacao_id IS NULL OR codigo_avaliacao IS NULL OR inicio IS NULL OR fim IS NULL OR NOT isfinite(inicio) OR NOT isfinite(fim) OR inicio>=fim THEN RETURN false; END IF;
 SELECT m."ativadaEm",e."limiteVinculo",a.ativa,a."provenienciaVinculo",a."inicioVigencia" AT TIME ZONE 'UTC',a."fimVigencia" AT TIME ZONE 'UTC',a."encerradaEm",a."criadoEm" INTO ativada_em,limite_vinculo,alocacao_ativa,proveniencia,inicio_vigencia,fim_vigencia,encerrada_em,criada_em FROM "Matricula" m JOIN "AlocacaoTurma" a ON a.id=alocacao_id AND a."matriculaId"=m.id LEFT JOIN "RegistroEncerramentoMatricula" e ON e."matriculaId"=m.id WHERE m.id=matricula_id;
 IF NOT FOUND OR (limite_vinculo IS NOT NULL AND NOT isfinite(limite_vinculo)) OR (inicio_vigencia IS NOT NULL AND NOT isfinite(inicio_vigencia)) OR (fim_vigencia IS NOT NULL AND NOT isfinite(fim_vigencia)) OR (encerrada_em IS NOT NULL AND NOT isfinite(encerrada_em)) THEN RETURN false; END IF;
 SELECT EXISTS(SELECT 1 FROM "FatoSituacaoMatriculaMigracao" f WHERE f."matriculaId"=matricula_id) INTO ha_fatos;
 -- Legado Q151: conserva ativadaEm obrigatório e a exceção especial mesmo com alocação inativa.
 IF NOT ha_fatos THEN
  IF ativada_em IS NULL OR NOT isfinite(ativada_em) THEN RETURN false; END IF;
  FOR ponto IN SELECT DISTINCT x.instante FROM (SELECT v.instante FROM (VALUES(inicio),(fim-interval '1 microsecond'),(ativada_em),(limite_vinculo))v(instante) UNION ALL SELECT ((p.snapshot->>'dataEfetiva')::date::timestamp AT TIME ZONE(p.snapshot->>'fusoInstitucional')) AT TIME ZONE 'UTC' FROM "ItemPropostaPausa" i JOIN "PropostaPausaMatriculas" p ON p.id=i."propostaId" WHERE i."matriculaId"=matricula_id AND p.status='APLICADA' UNION ALL SELECT ((p.snapshot->>'retorno')::date::timestamp AT TIME ZONE(p.snapshot->>'fusoInstitucional')) AT TIME ZONE 'UTC' FROM "ItemPropostaRetomadaMatriculas" i JOIN "PropostaRetomadaMatriculas" p ON p.id=i."propostaId" WHERE i."matriculaId"=matricula_id AND p.status='APLICADA' UNION ALL SELECT ae."criadaEm" FROM "AutorizacaoEspecialSegundaChamada" ae WHERE ae."alocacaoId"=alocacao_id AND ae."codigoAvaliacao"=codigo_avaliacao UNION ALL SELECT ae."prazoAte"+interval '1 microsecond' FROM "AutorizacaoEspecialSegundaChamada" ae WHERE ae."alocacaoId"=alocacao_id AND ae."codigoAvaliacao"=codigo_avaliacao)x WHERE x.instante IS NOT NULL AND isfinite(x.instante) AND x.instante>=inicio AND x.instante<fim ORDER BY instante LOOP
   situacao:=situacao_matricula_no_instante(matricula_id,ponto.instante); IF situacao='ATIVA' THEN IF alocacao_ativa IS NOT TRUE THEN RETURN false; END IF; ELSIF situacao IN('PAUSADA','ENCERRADA') THEN IF NOT autorizacao_especial_segunda_chamada_valida(alocacao_id,codigo_avaliacao,ponto.instante) THEN RETURN false; END IF; ELSE RETURN false; END IF;
  END LOOP; RETURN true;
 END IF;
 -- M01: fatos dispensam ativadaEm. Antes do início nunca há exceção; fim/encerradaEm só vedam ATIVA, preservando Q151 após encerramento.
 IF proveniencia='MIGRACAO'::"ProvenienciaVinculoMatricula" THEN inicio_alocacao:=inicio_vigencia; ELSE inicio_alocacao:=criada_em; END IF; IF inicio_alocacao IS NULL OR NOT isfinite(inicio_alocacao) THEN RETURN false; END IF;
 FOR ponto IN SELECT DISTINCT x.instante FROM (SELECT v.instante FROM (VALUES(inicio),(fim-interval '1 microsecond'),(inicio_alocacao),(fim_vigencia),(encerrada_em),(limite_vinculo))v(instante) UNION ALL SELECT f."efetivoEm" AT TIME ZONE 'UTC' FROM "FatoSituacaoMatriculaMigracao" f WHERE f."matriculaId"=matricula_id UNION ALL SELECT ((p.snapshot->>'dataEfetiva')::date::timestamp AT TIME ZONE(p.snapshot->>'fusoInstitucional')) AT TIME ZONE 'UTC' FROM "ItemPropostaPausa" i JOIN "PropostaPausaMatriculas" p ON p.id=i."propostaId" WHERE i."matriculaId"=matricula_id AND p.status='APLICADA' UNION ALL SELECT ((p.snapshot->>'retorno')::date::timestamp AT TIME ZONE(p.snapshot->>'fusoInstitucional')) AT TIME ZONE 'UTC' FROM "ItemPropostaRetomadaMatriculas" i JOIN "PropostaRetomadaMatriculas" p ON p.id=i."propostaId" WHERE i."matriculaId"=matricula_id AND p.status='APLICADA' UNION ALL SELECT ae."criadaEm" FROM "AutorizacaoEspecialSegundaChamada" ae WHERE ae."alocacaoId"=alocacao_id AND ae."codigoAvaliacao"=codigo_avaliacao UNION ALL SELECT ae."prazoAte"+interval '1 microsecond' FROM "AutorizacaoEspecialSegundaChamada" ae WHERE ae."alocacaoId"=alocacao_id AND ae."codigoAvaliacao"=codigo_avaliacao)x WHERE x.instante IS NOT NULL AND isfinite(x.instante) AND x.instante>=inicio AND x.instante<fim ORDER BY instante LOOP
  IF ponto.instante<inicio_alocacao THEN RETURN false; END IF; situacao:=situacao_matricula_no_instante(matricula_id,ponto.instante); IF situacao='ATIVA' THEN IF NOT EXISTS(SELECT 1 FROM "AlocacaoTurma" a WHERE a.id=alocacao_id AND alocacao_cobre_instante(a,ponto.instante AT TIME ZONE 'UTC')) THEN RETURN false; END IF; ELSIF situacao IN('PAUSADA','ENCERRADA') THEN IF NOT autorizacao_especial_segunda_chamada_valida(alocacao_id,codigo_avaliacao,ponto.instante) THEN RETURN false; END IF; ELSE RETURN false; END IF;
 END LOOP; RETURN true;
EXCEPTION WHEN OTHERS THEN RETURN false;
END $$;
