CREATE OR REPLACE FUNCTION preservar_reserva_tentativa_recuperacao() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE p "PropostaPlanoRecuperacao"%ROWTYPE; limite BIGINT; ocupadas BIGINT; autorizacao "AutorizacaoEspecialReservaRecuperacao"%ROWTYPE;
BEGIN
 IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'Reserva de tentativa é imutável'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('calendario-escola',0));
 IF TG_TABLE_NAME='ReservaTentativaRecuperacao' THEN
  SELECT * INTO p FROM "PropostaPlanoRecuperacao" WHERE id=NEW."propostaId";
  PERFORM id FROM "Matricula" WHERE id=p."matriculaId" FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Matrícula não encontrada'; END IF;
  PERFORM id FROM "Usuario" WHERE id=NEW."autorId" AND ativo AND papeis && ARRAY['GERENTE_PEDAGOGICO','ADMINISTRADOR']::"Papel"[] FOR SHARE; IF NOT FOUND THEN RAISE EXCEPTION 'Reserva exige gestão ativa'; END IF;
  IF NOT EXISTS(SELECT 1 FROM "DecisaoPlanoRecuperacao" WHERE "propostaId"=p.id AND aprovada) OR NOT EXISTS(SELECT 1 FROM "DisponibilizacaoPlanoRecuperacao" d WHERE "propostaId"=p.id AND d."disponibilizadaEm"<=clock_timestamp() AT TIME ZONE 'UTC' AND prazo_recuperacao_vigente(d.id)>clock_timestamp() AT TIME ZONE 'UTC') OR NOT EXISTS(SELECT 1 FROM "AlocacaoTurma" x JOIN "Turma" t ON t.id=x."turmaId" WHERE x.id=p."alocacaoId" AND x."matriculaId"=p."matriculaId" AND t."nivelId"=p."nivelId" AND t."regraAvaliacaoId"=p."regraId") THEN RAISE EXCEPTION 'Fonte da reserva inválida'; END IF;
  IF NEW."autorizacaoEspecialReservaId" IS NULL THEN
   IF NOT EXISTS(SELECT 1 FROM "Matricula" m JOIN "AlocacaoTurma" x ON x."matriculaId"=m.id WHERE m.id=p."matriculaId" AND m.status='ATIVA' AND x.id=p."alocacaoId" AND x.ativa) THEN RAISE EXCEPTION 'Reserva exige matrícula e vínculo ativos'; END IF;
  ELSE
   SELECT * INTO autorizacao FROM "AutorizacaoEspecialReservaRecuperacao" WHERE id=NEW."autorizacaoEspecialReservaId" FOR SHARE;
   IF NOT FOUND OR autorizacao."propostaId" IS DISTINCT FROM p.id OR NOT isfinite(autorizacao."prazoAte") OR autorizacao."criadaEm">clock_timestamp() AT TIME ZONE 'UTC' OR autorizacao."prazoAte"<=clock_timestamp() AT TIME ZONE 'UTC' OR NOT EXISTS(SELECT 1 FROM "Usuario" WHERE id=autorizacao."autorizadorId" AND ativo AND papeis && ARRAY['GERENTE_PEDAGOGICO','ADMINISTRADOR']::"Papel"[] FOR SHARE) OR NOT EXISTS(SELECT 1 FROM "Matricula" WHERE id=p."matriculaId" AND status IN ('PAUSADA','ENCERRADA')) OR autorizacao.snapshot IS DISTINCT FROM jsonb_build_object('matriculaId',p."matriculaId",'alocacaoId',p."alocacaoId",'regraId',p."regraId",'propostaId',p.id,'propostaHash',p."entradaHash",'decisaoId',(SELECT id FROM "DecisaoPlanoRecuperacao" WHERE "propostaId"=p.id AND aprovada),'disponibilizacaoId',(SELECT id FROM "DisponibilizacaoPlanoRecuperacao" WHERE "propostaId"=p.id),'habilidade',autorizacao.habilidade,'statusMatricula',(SELECT status::text FROM "Matricula" WHERE id=p."matriculaId")) THEN RAISE EXCEPTION 'Autorização especial de reserva inválida'; END IF;
  END IF;
 ELSE
  SELECT plano.* INTO p FROM "ReservaTentativaRecuperacao" r JOIN "PropostaPlanoRecuperacao" plano ON plano.id=r."propostaId" WHERE r.id=NEW."reservaId";
  PERFORM id FROM "Matricula" WHERE id=p."matriculaId" FOR UPDATE;
  IF EXISTS(SELECT 1 FROM "CancelamentoReservaRecuperacao" WHERE "reservaId"=NEW."reservaId") OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(p.atividades) x WHERE x->>'habilidade'=NEW.habilidade) THEN RAISE EXCEPTION 'Item de reserva inválido'; END IF;
  IF EXISTS(SELECT 1 FROM "ReservaTentativaRecuperacao" r JOIN "AutorizacaoEspecialReservaRecuperacao" a ON a.id=r."autorizacaoEspecialReservaId" WHERE r.id=NEW."reservaId" AND (a.habilidade IS DISTINCT FROM NEW.habilidade OR a."propostaId" IS DISTINCT FROM p.id OR NOT isfinite(a."prazoAte") OR a."criadaEm">clock_timestamp() AT TIME ZONE 'UTC' OR a."prazoAte"<=clock_timestamp() AT TIME ZONE 'UTC' OR EXISTS(SELECT 1 FROM "RealizacaoRecuperacao" z JOIN "ItemReservaTentativaRecuperacao" i ON i.id=z."itemReservaId" WHERE i."reservaId"=r.id) OR NOT EXISTS(SELECT 1 FROM "Usuario" u WHERE u.id=a."autorizadorId" AND u.ativo AND u.papeis && ARRAY['GERENTE_PEDAGOGICO','ADMINISTRADOR']::"Papel"[] FOR SHARE) OR NOT EXISTS(SELECT 1 FROM "Matricula" m JOIN "AlocacaoTurma" x ON x."matriculaId"=m.id JOIN "Turma" t ON t.id=x."turmaId" WHERE m.id=p."matriculaId" AND m.status IN ('PAUSADA','ENCERRADA') AND x.id=p."alocacaoId" AND t."nivelId"=p."nivelId" AND t."regraAvaliacaoId"=p."regraId") OR NOT EXISTS(SELECT 1 FROM "DisponibilizacaoPlanoRecuperacao" d WHERE d."propostaId"=p.id AND d."disponibilizadaEm"<=clock_timestamp() AT TIME ZONE 'UTC' AND prazo_recuperacao_vigente(d.id)>clock_timestamp() AT TIME ZONE 'UTC') OR a.snapshot IS DISTINCT FROM jsonb_build_object('matriculaId',p."matriculaId",'alocacaoId',p."alocacaoId",'regraId',p."regraId",'propostaId',p.id,'propostaHash',p."entradaHash",'decisaoId',(SELECT id FROM "DecisaoPlanoRecuperacao" WHERE "propostaId"=p.id AND aprovada),'disponibilizacaoId',(SELECT id FROM "DisponibilizacaoPlanoRecuperacao" WHERE "propostaId"=p.id),'habilidade',a.habilidade,'statusMatricula',(SELECT status::text FROM "Matricula" WHERE id=p."matriculaId")))) THEN RAISE EXCEPTION 'Autorização especial não permite esta habilidade'; END IF;
  SELECT (h->>'limiteRecuperacoes')::bigint INTO limite FROM "VersaoRegraAvaliacao" regra,jsonb_array_elements(regra.conteudo->'habilidades') h WHERE regra.id=p."regraId" AND h->>'habilidade'=NEW.habilidade;
  SELECT count(*) INTO ocupadas FROM "ItemReservaTentativaRecuperacao" i JOIN "ReservaTentativaRecuperacao" r ON r.id=i."reservaId" JOIN "PropostaPlanoRecuperacao" q ON q.id=r."propostaId" WHERE q."matriculaId"=p."matriculaId" AND q."nivelId"=p."nivelId" AND i.habilidade=NEW.habilidade AND (NOT EXISTS(SELECT 1 FROM "CancelamentoReservaRecuperacao" c WHERE c."reservaId"=r.id) OR EXISTS(SELECT 1 FROM "RealizacaoRecuperacao" z WHERE z."itemReservaId"=i.id));
  limite:=limite+(SELECT coalesce(sum(e.quantidade),0) FROM "PropostaExtraRecuperacao" e JOIN "DecisaoExtraRecuperacao" d ON d."propostaId"=e.id AND d.aprovada WHERE e."matriculaId"=p."matriculaId" AND e."nivelId"=p."nivelId" AND e.habilidade=NEW.habilidade);
  IF limite IS NULL OR ocupadas>=limite THEN RAISE EXCEPTION 'Limite de tentativas da habilidade esgotado'; END IF;
 END IF; RETURN NEW;
END $$;
