"use server";

/* Destination: src/server/migracao/conciliacao-financeira.ts
 * The transaction deliberately does not call any emitter/transport. */
import { FormaPagamento, Papel, Prisma } from "@prisma/client";
import { randomUUID } from "crypto";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { executarAcao, exigirSessaoComPapel, ErroPermissao, ErroRegra, registrarEvento } from "@/server/_shared";
import { receberTx } from "@/server/financeiro/recebimentos";
import { hashFotografiaFinanceira } from "./fotografia-financeira";
import { fotografiaConciliacaoFinanceiraTx } from "./fotografia-conciliacao-financeira";
import { ComplementoConciliacaoFinanceiraSchema, validarFonteConciliacaoFinanceira } from "./fonte-conciliacao-financeira";

const evidencias = z.record(z.string().trim().min(1), z.union([z.string().trim().min(1), z.number().finite(), z.boolean()])).refine(x => Object.keys(x).length > 0, "Informe evidência verificável.");
const propostaEntrada = z.object({
  linhaId:z.string().min(1), matriculaId:z.string().min(1), cobrancaId:z.string().min(1), pagadorId:z.string().min(1),
  modalidade:z.enum(["PENDENCIA","VINCULAR_RECEBIMENTO","BAIXAR"]), valor:z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), moeda:z.string().regex(/^[A-Z]{3}$/).optional(),
  dataPagamento:z.string().datetime({ offset:true }).optional(), forma:z.nativeEnum(FormaPagamento).optional(), recebimentoExistenteId:z.string().min(1).optional(),
  evidencia:evidencias, complemento:ComplementoConciliacaoFinanceiraSchema.optional(), chaveIdempotencia:z.string().uuid(),
}).strict().superRefine((v,c) => { const pagamento=v.modalidade!=="PENDENCIA"; if(pagamento && (!v.valor||!v.moeda||!v.dataPagamento||!v.forma)) c.addIssue({code:"custom",message:"Valor, moeda, data histórica e forma exigem fonte ou complemento evidenciado."}); if(v.modalidade==="VINCULAR_RECEBIMENTO"&&!v.recebimentoExistenteId)c.addIssue({code:"custom",message:"Informe o recebimento ERP a conferir."}); if(v.modalidade!=="VINCULAR_RECEBIMENTO"&&v.recebimentoExistenteId)c.addIssue({code:"custom",message:"Recebimento existente só pode ser vinculado, não baixado novamente."}); });
const decisaoEntrada=z.object({propostaId:z.string().min(1), aprovada:z.boolean(), motivo:z.string().trim().min(10).max(1000), chaveIdempotencia:z.string().uuid()}).strict();
const hash=hashFotografiaFinanceira;
const entradaPersistida = (dados: z.output<typeof propostaEntrada>) => ({ ...Object.fromEntries(Object.entries(dados).filter(([, valor]) => valor !== undefined)), dataPagamento: dados.dataPagamento ?? null });

async function financeiroFresco(tx:Prisma.TransactionClient,id:string) { const [u]=await tx.$queryRaw<{ativo:boolean;papeis:Papel[]}[]>(Prisma.sql`SELECT ativo,papeis FROM "Usuario" WHERE id=${id} FOR SHARE`); if(!u?.ativo||!(u.papeis.includes(Papel.ADMINISTRADOR)||u.papeis.includes(Papel.FINANCEIRO))) throw new ErroPermissao("Exige perfil financeiro ativo."); return u; }

export async function proporConciliacaoFinanceiraMigracao(input:unknown) { return executarAcao(async()=>{ const autor=await exigirSessaoComPapel(Papel.ADMINISTRADOR,Papel.FINANCEIRO); const d=propostaEntrada.parse(input); return prisma.$transaction(async tx=>{
  await financeiroFresco(tx,autor.id);
  const [linha]=await tx.$queryRaw<{id:string;origem:string;financeiroOrigemId:string;matriculaOrigemId:string|null;entradaHash:string;dadosOrigem:unknown}[]>(Prisma.sql`SELECT l.id,lo.origem,l."financeiroOrigemId",l."matriculaOrigemId",l."entradaHash",l."dadosOrigem" FROM "LinhaPreparacaoMigracao" l JOIN "LotePreparacaoMigracao" lo ON lo.id=l."loteId" WHERE l.id=${d.linhaId} AND l."tipoEntrada"='FINANCEIRO_HISTORICO'::"TipoEntradaPreparacaoMigracao" FOR UPDATE`);
  if(!linha?.financeiroOrigemId||!linha.matriculaOrigemId) throw new ErroRegra("A origem financeira precisa identificar registro e contrato; complete a fonte antes de conciliar.");
  await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`migracao-financeiro:${linha.origem}:${linha.financeiroOrigemId}`},0))`;
  const repetida=await tx.propostaConciliacaoFinanceiraMigracao.findUnique({where:{preparadorId_chaveIdempotencia:{preparadorId:autor.id,chaveIdempotencia:d.chaveIdempotencia}}}); if(repetida) { const entradaRepetida=entradaPersistida(d); if(repetida.entradaHash!==hash(entradaRepetida)) throw new ErroRegra("A chave idempotente já representa outra conciliação."); return {id:repetida.id,repetida:true}; }
  const aplicacoesOrigem=await tx.conciliacaoFinanceiraMigracao.findMany({where:{origem:linha.origem,financeiroOrigemId:linha.financeiroOrigemId},select:{recebimentoId:true}});
  if(aplicacoesOrigem.some(aplicacao=>aplicacao.recebimentoId!==null)) throw new ErroRegra("Esta origem já foi conciliada com recebimento; não pode ser conciliada novamente.");
  if(d.modalidade==="PENDENCIA"&&aplicacoesOrigem.length>0) throw new ErroRegra("A pendência desta origem já foi registrada; concilie o recebimento quando houver evidência.");
  const fresco=await fotografiaConciliacaoFinanceiraTx(tx,{linhaId:d.linhaId,matriculaId:d.matriculaId,cobrancaId:d.cobrancaId,pagadorId:d.pagadorId,recebimentoId:d.recebimentoExistenteId});
  const {mapa:contrato,cobranca,pagador,recebimento:existente}=fresco;
  if(contrato?.matriculaId!==d.matriculaId||cobranca?.matriculaId!==d.matriculaId||pagador?.matriculaId!==d.matriculaId) throw new ErroRegra("Contrato, cobrança e pagador devem ser a associação explícita da mesma matrícula migrada.");
  if(d.modalidade!=="PENDENCIA" && (!d.valor||!d.moeda||!d.dataPagamento||!d.forma||cobranca.moeda!==d.moeda)) throw new ErroRegra("A fonte/complemento precisa confirmar valor, moeda, data, forma e compatibilidade com a cobrança.");
  validarFonteConciliacaoFinanceira({ modalidade:d.modalidade, valor:d.valor, moeda:d.moeda, dataPagamento:d.dataPagamento, forma:d.forma, pagadorId:d.pagadorId, tipoCobranca:cobranca.tipo, dadosOrigem:fresco.linha.dadosOrigem, complemento:d.complemento });
  if(d.modalidade==="VINCULAR_RECEBIMENTO" && (!existente||existente.cobrancaId!==cobranca.id||!existente.valor.equals(new Prisma.Decimal(d.valor!))||existente.moeda!==d.moeda||existente.forma!==d.forma||existente.dataPagamento.toISOString()!==new Date(d.dataPagamento!).toISOString())) throw new ErroRegra("O recebimento ERP não corresponde à fotografia declarada; não será vinculado.");
  const entrada=entradaPersistida(d); const snapshot=fresco.foto;
  const ultima=await tx.propostaConciliacaoFinanceiraMigracao.findFirst({where:{origem:linha.origem,financeiroOrigemId:linha.financeiroOrigemId},orderBy:{versao:"desc"},select:{versao:true}});
  const p=await tx.propostaConciliacaoFinanceiraMigracao.create({data:{id:randomUUID(),origem:linha.origem,financeiroOrigemId:linha.financeiroOrigemId,versao:(ultima?.versao??0)+1,linhaId:linha.id,matriculaId:d.matriculaId,cobrancaId:d.cobrancaId,pagadorId:d.pagadorId,preparadorId:autor.id,modalidade:d.modalidade,valor:d.valor?new Prisma.Decimal(d.valor):null,moeda:d.moeda??null,dataPagamento:d.dataPagamento?new Date(d.dataPagamento):null,forma:d.forma??null,recebimentoExistenteId:d.recebimentoExistenteId??null,evidencia:d.evidencia,complemento:d.complemento??Prisma.DbNull,entrada,snapshot,entradaHash:hash(entrada),estadoHash:fresco.hash,chaveIdempotencia:d.chaveIdempotencia}});
  await registrarEvento(tx,{tipo:"PropostaConciliacaoFinanceiraMigracao",agregadoTipo:"LotePreparacaoMigracao",agregadoId:(await tx.linhaPreparacaoMigracao.findUniqueOrThrow({where:{id:linha.id},select:{loteId:true}})).loteId,autorId:autor.id,payload:{propostaId:p.id,linhaId:linha.id,origem:linha.origem,financeiroOrigemId:linha.financeiroOrigemId,modalidade:d.modalidade}}); return {id:p.id,repetida:false};
 }); }); }

export async function decidirConciliacaoFinanceiraMigracao(input:unknown) { return executarAcao(async()=>{const decisor=await exigirSessaoComPapel(Papel.ADMINISTRADOR,Papel.FINANCEIRO); const d=decisaoEntrada.parse(input); return prisma.$transaction(async tx=>{
 await financeiroFresco(tx,decisor.id); const [bloqueada]=await tx.$queryRaw<{id:string}[]>(Prisma.sql`SELECT id FROM "PropostaConciliacaoFinanceiraMigracao" WHERE id=${d.propostaId} FOR UPDATE`); if(!bloqueada) throw new ErroRegra("Proposta não encontrada."); const atual=await tx.propostaConciliacaoFinanceiraMigracao.findUniqueOrThrow({where:{id:d.propostaId},include:{cobranca:true,pagador:true,recebimentoExistente:true}}); if(atual.preparadorId===decisor.id)throw new ErroPermissao("A decisão exige outro usuário financeiro."); if(atual.status!=="PENDENTE") { if(atual.decisorId===decisor.id&&atual.chaveDecisao===d.chaveIdempotencia&&atual.motivoDecisao===d.motivo&&((d.aprovada&&atual.status==="APLICADA")||(!d.aprovada&&atual.status==="REJEITADA"))) return {id:atual.id,repetida:true}; throw new ErroRegra("A proposta já recebeu uma decisão diferente."); } if(!d.aprovada){await tx.propostaConciliacaoFinanceiraMigracao.update({where:{id:atual.id},data:{status:"REJEITADA",decisorId:decisor.id,chaveDecisao:d.chaveIdempotencia,motivoDecisao:d.motivo,decididoEm:new Date()}});return{id:atual.id,rejeitada:true};}
 // Revalidação só na aprovação. Nunca se usa a data corrente como data de pagamento.
 const fresca=await fotografiaConciliacaoFinanceiraTx(tx,{linhaId:atual.linhaId,matriculaId:atual.matriculaId,cobrancaId:atual.cobrancaId,pagadorId:atual.pagadorId,recebimentoId:atual.recebimentoExistenteId}); if(fresca.hash!==atual.estadoHash) throw new ErroRegra("A fotografia da fonte, contrato, cobrança, pagador ou recebimento mudou; crie nova proposta.");
 const entradaPersistida=atual.entrada as Record<string,unknown>; const entradaOriginal=propostaEntrada.parse({...entradaPersistida,dataPagamento:entradaPersistida.dataPagamento??undefined}); validarFonteConciliacaoFinanceira({ modalidade:entradaOriginal.modalidade, valor:entradaOriginal.valor, moeda:entradaOriginal.moeda, dataPagamento:entradaOriginal.dataPagamento, forma:entradaOriginal.forma, pagadorId:entradaOriginal.pagadorId, tipoCobranca:fresca.cobranca.tipo, dadosOrigem:fresca.linha.dadosOrigem, complemento:entradaOriginal.complemento }); const agora=fresca.cobranca;
 let recebimentoId:string|null=null;
 if(atual.modalidade==="VINCULAR_RECEBIMENTO")recebimentoId=atual.recebimentoExistenteId!;
 await tx.propostaConciliacaoFinanceiraMigracao.update({where:{id:atual.id},data:{status:"APROVADA",decisorId:decisor.id,chaveDecisao:d.chaveIdempotencia,motivoDecisao:d.motivo,decididoEm:new Date()}}); if(atual.modalidade==="BAIXAR"){const r=await receberTx(tx,{cobrancaId:atual.cobrancaId,autorId:decisor.id,valorRecebido:atual.valor!.toNumber(),moeda:atual.moeda!,forma:atual.forma!,dataPagamento:atual.dataPagamento!,chaveIdempotencia:`m01-financeiro:${atual.id}`,hashDados:hash({propostaId:atual.id,estadoHash:atual.estadoHash}),comprovanteUrl:agora.comprovanteUrl,comprovanteNome:agora.comprovanteNome,comentario:agora.comentario}); recebimentoId=r.id;} await tx.conciliacaoFinanceiraMigracao.create({data:{id:randomUUID(),origem:atual.origem,financeiroOrigemId:atual.financeiroOrigemId,propostaId:atual.id,recebimentoId,aplicadaPorId:decisor.id,snapshot:{propostaId:atual.id,estadoHash:atual.estadoHash,registroERP:recebimentoId,dataHistorica:atual.dataPagamento?.toISOString()??null}}}); await tx.propostaConciliacaoFinanceiraMigracao.update({where:{id:atual.id},data:{status:"APLICADA",aplicadaEm:new Date()}}); await registrarEvento(tx,{tipo:"ConciliacaoFinanceiraMigracaoAplicada",agregadoTipo:"Cobranca",agregadoId:atual.cobrancaId,autorId:decisor.id,payload:{propostaId:atual.id,origem:atual.origem,financeiroOrigemId:atual.financeiroOrigemId,modalidade:atual.modalidade,recebimentoId,dataHistorica:atual.dataPagamento?.toISOString()??null}}); return{id:atual.id,recebimentoId};
 }); }); }
