"use server";
import ExcelJS from "exceljs";
import { Papel } from "@prisma/client";
import { z } from "zod";
import { executarAcao, exigirSessaoComPapel } from "@/server/_shared";
import { prepararLoteMigracao } from "./acoes";
import { lerCsvPreparacao, linhasMapeadasPreparacao, type AbaPlanilha, type MapeamentoMigracao } from "./planilha";

const LIMITE_BYTES = 5 * 1024 * 1024; const LIMITE_LINHAS = 500;
const Entrada = z.object({ origem: z.string().trim().min(1).max(120), chaveLote: z.string().trim().min(1).max(120), aba: z.number().int().min(0).max(99), mapeamento: z.record(z.string(), z.string().regex(/^c\d+$/).optional()), tipoEntrada: z.enum(["CADASTRO", "VINCULO_MATRICULA", "FINANCEIRO_HISTORICO", "HISTORICO_PRESENCA"]), delimitador: z.enum([",", ";"]).optional() }).strict();
function texto(valor: ExcelJS.CellValue) { if (valor == null) return null; if (valor instanceof Date) return valor.toISOString().slice(0, 10); if (typeof valor === "object") { if ("formula" in valor) return `fórmula: ${valor.formula}; resultado: ${String(valor.result ?? "")}`; if ("richText" in valor && Array.isArray(valor.richText)) return valor.richText.map((parte) => parte.text).join(""); if ("text" in valor && valor.text != null) return String(valor.text); if ("error" in valor) return `erro: ${String(valor.error)}`; return JSON.stringify(valor); } return typeof valor === "number" ? valor : String(valor); }
export async function lerArquivoPreparacao(file: File, delimitador?: string): Promise<AbaPlanilha[]> {
  if (file.size === 0 || file.size > LIMITE_BYTES) throw new Error("Arquivo ausente ou acima de 5MB.");
  if (/\.csv$/i.test(file.name)) return [lerCsvPreparacao(await file.text(), file.name, delimitador === ";" ? ";" : delimitador === "," ? "," : undefined)];
  if (!/\.xlsx$/i.test(file.name)) throw new Error("Use um arquivo CSV ou XLSX.");
  const livro = new ExcelJS.Workbook(); await livro.xlsx.load(await file.arrayBuffer());
  return livro.worksheets.map((sheet) => { if (sheet.rowCount - 1 > LIMITE_LINHAS) throw new Error(`Aba ${sheet.name} tem mais de ${LIMITE_LINHAS} linhas; separe a origem em lotes explícitos.`); const usados = new Set<string>(); const cabecalhos = Array.from({ length: sheet.columnCount }, (_, indice) => { const base = String(texto(sheet.getRow(1).getCell(indice + 1).value) ?? "").trim() || `Coluna ${indice + 1}`; let rotulo = base, repeticao = 2; while (usados.has(rotulo)) rotulo = `${base} (${repeticao++})`; usados.add(rotulo); return { id: `c${indice + 1}`, rotulo }; }); const linhas = Array.from({ length: Math.max(sheet.rowCount - 1, 0) }, (_, indice) => { const numero = indice + 2, row = sheet.getRow(numero), valores = Object.fromEntries(cabecalhos.map((cabecalho, coluna) => { const cell = row.getCell(coluna + 1); return [cabecalho.id, typeof cell.value === "number" ? cell.text : texto(cell.value)]; })); return { numero, valores }; }).filter((linha) => Object.values(linha.valores).some((valor) => valor !== null && valor !== "")); return { nome: sheet.name, cabecalhos, linhas }; });
}
export async function preverArquivoPreparacaoMigracao(form: FormData, delimitador?: "," | ";") { return executarAcao(async () => { await exigirSessaoComPapel(Papel.ADMINISTRADOR); const file = form.get("arquivo"); if (!(file instanceof File)) throw new Error("Selecione um arquivo."); return lerArquivoPreparacao(file, delimitador); }); }
export async function prepararArquivoMigracao(form: FormData, entrada: { origem: string; chaveLote: string; aba: number; mapeamento: MapeamentoMigracao; tipoEntrada: "CADASTRO" | "VINCULO_MATRICULA" | "FINANCEIRO_HISTORICO" | "HISTORICO_PRESENCA"; delimitador?: "," | ";" }) { return executarAcao(async () => { await exigirSessaoComPapel(Papel.ADMINISTRADOR); const dados = Entrada.parse(entrada); const file = form.get("arquivo"); if (!(file instanceof File)) throw new Error("Selecione um arquivo."); const abas = await lerArquivoPreparacao(file, dados.delimitador); const aba = abas[dados.aba]; if (!aba) throw new Error("Aba não encontrada no arquivo."); const colunas = new Set(aba.cabecalhos.map((cabecalho) => cabecalho.id)); const selecionadas = Object.values(dados.mapeamento).filter((id): id is string => !!id); if (selecionadas.some((id) => !colunas.has(id))) throw new Error("O mapeamento referencia uma coluna que não existe nesta aba."); if (new Set(selecionadas).size !== selecionadas.length) throw new Error("Uma coluna só pode ser mapeada para um campo por vez."); const preparado = await prepararLoteMigracao({ origem: dados.origem, chaveLote: dados.chaveLote, linhas: linhasMapeadasPreparacao(aba, dados.mapeamento, dados.tipoEntrada) }); if (!preparado.ok) throw new Error(preparado.erro); return preparado.dado; }); }
