import ExcelJS from "exceljs";
import { beforeEach, expect, it, vi } from "vitest";
import { Papel } from "@prisma/client";
const { authMock } = vi.hoisted(() => ({ authMock: vi.fn() }));
vi.mock("@/lib/auth", () => ({ auth: authMock }));
vi.mock("@/server/_shared/sessao", async (original) => { const real = await original<typeof import("@/server/_shared/sessao")>(); const { prisma } = await import("@/lib/prisma"); async function sessao() { const id = (await authMock())?.user?.id; const u = id && await prisma.usuario.findUnique({ where: { id }, select: { id: true, nome: true, ativo: true, papeis: true } }); if (!u?.ativo) throw new real.ErroAutenticacao(); return u; } return { ...real, exigirSessao: sessao, exigirSessaoComPapel: async (...p: Papel[]) => { const u = await sessao(); real.exigirPapel(u, ...p); return u; } }; });
import { prisma } from "@/lib/prisma"; import { criarUsuario, truncarBanco } from "@/test/integracao"; import { prepararArquivoMigracao } from "./planilha-acoes";
async function formXlsx() { const w = new ExcelJS.Workbook(); const s = w.addWorksheet("Dados"); ["id","nome","extra"].forEach((v,i)=>s.getCell(1,i+1).value=v); s.getCell("A2").value="001"; s.getCell("B2").value={richText:[{text:"Á"},{text:"na"}]}; s.getCell("C2").value={formula:"1+1",result:2}; const f=new FormData(); f.set("arquivo", new File([new Uint8Array(await w.xlsx.writeBuffer())],"dados.xlsx")); return f; }
beforeEach(async()=>{await truncarBanco(); const u=await criarUsuario([Papel.ADMINISTRADOR]); authMock.mockResolvedValue({user:{id:u.id}});});
it("prepara XLSX real, persiste fotografia e devolve dado não aninhado",async()=>{const r=await prepararArquivoMigracao(await formXlsx(),{origem:"XLSX",chaveLote:"x1",aba:0,tipoEntrada:"CADASTRO",mapeamento:{"aluno.id":"c1","aluno.nome":"c2"}});expect(r).toMatchObject({ok:true,dado:{loteId:expect.any(String)}});expect((r as {dado?: {ok?:unknown}}).dado?.ok).toBeUndefined();const l=await prisma.linhaPreparacaoMigracao.findFirstOrThrow();expect(l.dadosOrigem).toMatchObject({aluno:{id:"001",nome:"Ána"},dadosAdicionais:{extra:"fórmula: 1+1; resultado: 2"}});});
it("rejeita mapeamento desconhecido sem gravar lote",async()=>{const r=await prepararArquivoMigracao(await formXlsx(),{origem:"XLSX",chaveLote:"x2",aba:0,tipoEntrada:"CADASTRO",mapeamento:{campoInventado:"c1"} as never});expect(r).toMatchObject({ok:false});expect(await prisma.lotePreparacaoMigracao.count()).toBe(0);});
