"use server";
import ExcelJS from "exceljs";
import { Papel } from "@prisma/client";
import { z } from "zod";
import { ErroRegra, executarAcao, exigirSessaoComPapel } from "@/server/_shared";
import { prepararLoteMigracao } from "./acoes";
import { CAMPOS_MIGRACAO, linhasMapeadasPreparacao, type MapeamentoMigracao } from "./planilha";
import { lerArquivoPreparacao } from "./planilha-leitura";

const Entrada = z.object({ origem: z.string().trim().min(1).max(120), chaveLote: z.string().trim().min(1).max(120), aba: z.number().int().min(0).max(99), mapeamento: z.object(Object.fromEntries(CAMPOS_MIGRACAO.map((campo) => [campo, z.string().regex(/^c\d+$/).optional()]))).strict(), tipoEntrada: z.enum(["CADASTRO", "VINCULO_MATRICULA", "FINANCEIRO_HISTORICO", "HISTORICO_PRESENCA"]), delimitador: z.enum([",", ";"]).optional() }).strict();
export async function preverArquivoPreparacaoMigracao(form: FormData, delimitador?: "," | ";") { return executarAcao(async () => { await exigirSessaoComPapel(Papel.ADMINISTRADOR); const file = form.get("arquivo"); if (!(file instanceof File)) throw new ErroRegra("Selecione um arquivo."); return lerArquivoPreparacao(file, delimitador); }); }
export async function prepararArquivoMigracao(form: FormData, entrada: { origem: string; chaveLote: string; aba: number; mapeamento: MapeamentoMigracao; tipoEntrada: "CADASTRO" | "VINCULO_MATRICULA" | "FINANCEIRO_HISTORICO" | "HISTORICO_PRESENCA"; delimitador?: "," | ";" }) { return executarAcao(async () => { await exigirSessaoComPapel(Papel.ADMINISTRADOR); const dados = Entrada.parse(entrada); const file = form.get("arquivo"); if (!(file instanceof File)) throw new ErroRegra("Selecione um arquivo."); const abas = await lerArquivoPreparacao(file, dados.delimitador); const aba = abas[dados.aba]; if (!aba) throw new ErroRegra("Aba não encontrada no arquivo."); const colunas = new Set(aba.cabecalhos.map((cabecalho) => cabecalho.id)); const selecionadas = Object.values(dados.mapeamento).filter((id): id is string => !!id); if (selecionadas.some((id) => !colunas.has(id))) throw new ErroRegra("O mapeamento referencia uma coluna que não existe nesta aba."); if (new Set(selecionadas).size !== selecionadas.length) throw new ErroRegra("Uma coluna só pode ser mapeada para um campo por vez."); const preparado = await prepararLoteMigracao({ origem: dados.origem, chaveLote: dados.chaveLote, linhas: linhasMapeadasPreparacao(aba, dados.mapeamento, dados.tipoEntrada) }); if (!preparado.ok) throw new ErroRegra(preparado.erro); return preparado.dado; }); }
