"use client";
import { useRef, useState, useTransition } from "react";
import { prepararAlteracaoQuantidadeAulasModalidade } from "@/server/agenda/modalidade-quantidade";
import { preverAlteracaoQuantidadeAulasModalidade } from "@/server/agenda/modalidade-quantidade-consulta";
import { FeedbackAcao } from "@/components/FeedbackAcao";
import { useAcaoCliente } from "@/lib/acao-cliente";
type Modalidade = { id: string; nome: string; aulasPorNivel: number | null };
type Previa = { podeAplicar: boolean; versaoAnterior: number; impactos: Array<{ turmaId: string; codigo: string | null; quantidadeVigente: number; quantidadeNova: number; alcance: string; causa: string; excecoesQ37: string[]; pendencias: string[]; parametrosGradeAprovada: { duracaoMinutos: number; frequencia: string | null; diasSemana: number[] } | null }> };
const nomeDia = ["domingo", "segunda-feira", "terça-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sábado"];
export function AlterarQuantidadeAulas({ modalidade }: { modalidade: Modalidade }) {
 const [quantidade, setQuantidade] = useState(String(modalidade.aulasPorNivel ?? "")), [motivo, setMotivo] = useState(""), [previa, setPrevia] = useState<Previa | null>(null), [erroPrevia, setErroPrevia] = useState<string | null>(null), [pendente, start] = useTransition();
 // A chave acompanha a entrada: reenviar a MESMA proposta após falha de rede confere a mesma revisão;
 // antes era um randomUUID() por clique, e o reenvio criava uma segunda proposta para a modalidade.
 const tentativa = useRef<{ assinatura: string; chave: string } | null>(null), acao = useAcaoCliente({ idempotente: true });
 const conferir = () => start(async () => { setErroPrevia(null); try { const r = await preverAlteracaoQuantidadeAulasModalidade({ modalidadeId: modalidade.id, quantidadeNova: Number(quantidade) }); if (!r.ok || !r.dado) setErroPrevia(r.ok ? "Prévia indisponível." : r.erro); else setPrevia(r.dado as Previa); } catch { setErroPrevia("A prévia não carregou. Tente conferir de novo."); } });
 const salvar = () => { if (!previa) return acao.setErro("Confira a prévia antes de preparar a revisão."); const dados = { modalidadeId: modalidade.id, quantidadeNova: Number(quantidade), versaoAnterior: previa.versaoAnterior, motivo }, assinatura = JSON.stringify(dados); if (tentativa.current?.assinatura !== assinatura) tentativa.current = { assinatura, chave: crypto.randomUUID() }; const chaveIdempotencia = tentativa.current.chave; void acao.executar(() => prepararAlteracaoQuantidadeAulasModalidade({ ...dados, chaveIdempotencia }), (dado) => { window.location.assign(`/academico/modalidades/${modalidade.id}/quantidade/propostas/${dado!.id}`); }); };
 return <section className="space-y-4 rounded border p-4"><label className="block">Nova quantidade de aulas<input className="ml-2 rounded border px-2 py-1" type="number" min={1} value={quantidade} onChange={(e) => { setQuantidade(e.target.value); setPrevia(null); }} /></label><button className="rounded border px-3 py-2" disabled={pendente} onClick={conferir}>Conferir impactos</button>{erroPrevia && <p role="alert">{erroPrevia}</p>}{previa && <><p>{previa.podeAplicar ? "Conjunto sem conflitos na conferência atual." : "Há pendências ou conflitos a resolver antes da aprovação."}</p><ul className="space-y-2">{previa.impactos.map((i) => <li key={i.turmaId} className="rounded border p-2"><strong>{i.codigo ?? i.turmaId}</strong> · {i.quantidadeVigente} → {i.quantidadeNova} · {i.alcance}<br/><span className="text-sm">{i.causa}{i.excecoesQ37.length && i.parametrosGradeAprovada ? ` Condições específicas da turma preservadas: ${i.parametrosGradeAprovada.duracaoMinutos} min · ${i.parametrosGradeAprovada.frequencia ?? `${i.parametrosGradeAprovada.diasSemana.length}x por semana`} · ${i.parametrosGradeAprovada.diasSemana.map((d) => nomeDia[d]).join(", ")}.` : ""}{i.pendencias.length ? ` Pendências: ${i.pendencias.join(" ")}` : ""}</span></li>)}</ul><label className="block">Motivo<input className="ml-2 w-96 rounded border px-2 py-1" value={motivo} onChange={(e) => setMotivo(e.target.value)} /></label><FeedbackAcao erro={acao.erro} /><button className="rounded bg-brand-solid px-3 py-2 text-white" disabled={pendente || acao.ocupado || motivo.trim().length < 5} onClick={salvar}>{acao.ocupado ? "Preparando…" : "Preparar revisão conjunta"}</button></>}</section>;
}
