"use client";
import { useRef, useState } from "react";
import { prepararAlteracaoQuantidadeAulasModalidade } from "@/server/agenda/modalidade-quantidade";
import { preverAlteracaoQuantidadeAulasModalidade } from "@/server/agenda/modalidade-quantidade-consulta";
import { FeedbackAcao } from "@/components/FeedbackAcao";
import { useAcaoCliente } from "@/lib/acao-cliente";
import { botaoClasses } from "@/components/Botao";
type Modalidade = { id: string; nome: string; aulasPorNivel: number | null };
type Previa = { podeAplicar: boolean; versaoAnterior: number; impactos: Array<{ turmaId: string; codigo: string | null; quantidadeVigente: number; quantidadeNova: number; alcance: string; causa: string; excecoesQ37: string[]; pendencias: string[]; parametrosGradeAprovada: { duracaoMinutos: number; frequencia: string | null; diasSemana: number[] } | null }> };
const nomeDia = ["domingo", "segunda-feira", "terça-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sábado"];
export function AlterarQuantidadeAulas({ modalidade }: { modalidade: Modalidade }) {
 const [quantidade, setQuantidade] = useState(String(modalidade.aulasPorNivel ?? "")), [motivo, setMotivo] = useState(""), [previa, setPrevia] = useState<Previa | null>(null);
 // A chave acompanha a entrada: reenviar a MESMA proposta após falha de rede confere a mesma revisão;
 // antes era um randomUUID() por clique, e o reenvio criava uma segunda proposta para a modalidade.
 // A prévia é só leitura — repetir é sempre seguro, por isso também `idempotente: true`.
 const tentativa = useRef<{ assinatura: string; chave: string } | null>(null), acao = useAcaoCliente({ idempotente: true }), previaAcao = useAcaoCliente({ idempotente: true });
 const conferir = async () => { const d = await previaAcao.executar(() => preverAlteracaoQuantidadeAulasModalidade({ modalidadeId: modalidade.id, quantidadeNova: Number(quantidade) })); if (d?.tipo !== "ok") return; if (!d.dado) previaAcao.setErro("Prévia indisponível."); else setPrevia(d.dado as Previa); };
 // O botão só existe com prévia carregada (ver JSX), então não há ramo "sem prévia" aqui.
 const salvar = async (p: Previa) => { const dados = { modalidadeId: modalidade.id, quantidadeNova: Number(quantidade), versaoAnterior: p.versaoAnterior, motivo }, assinatura = JSON.stringify(dados); if (tentativa.current?.assinatura !== assinatura) tentativa.current = { assinatura, chave: crypto.randomUUID() }; const chaveIdempotencia = tentativa.current.chave; const d = await acao.executar(() => prepararAlteracaoQuantidadeAulasModalidade({ ...dados, chaveIdempotencia })); if (d?.tipo === "ok") window.location.assign(`/academico/modalidades/${modalidade.id}/quantidade/propostas/${d.dado!.id}`); };
 return <section className="space-y-4 rounded border p-4"><label className="block">Nova quantidade de aulas<input className="ml-2 rounded border px-2 py-1" type="number" min={1} value={quantidade} onChange={(e) => { setQuantidade(e.target.value); setPrevia(null); }} /></label><button className={botaoClasses({ variante: "secundario", tamanho: "lg" })} disabled={previaAcao.ocupado || acao.ocupado} onClick={conferir}>{previaAcao.ocupado ? "Conferindo…" : "Conferir impactos"}</button><FeedbackAcao erro={previaAcao.erro} />{previa && <><p>{previa.podeAplicar ? "Conjunto sem conflitos na conferência atual." : "Há pendências ou conflitos a resolver antes da aprovação."}</p><ul className="space-y-2">{previa.impactos.map((i) => <li key={i.turmaId} className="rounded border p-2"><strong>{i.codigo ?? i.turmaId}</strong> · {i.quantidadeVigente} → {i.quantidadeNova} · {i.alcance}<br/><span className="text-sm">{i.causa}{i.excecoesQ37.length && i.parametrosGradeAprovada ? ` Condições específicas da turma preservadas: ${i.parametrosGradeAprovada.duracaoMinutos} min · ${i.parametrosGradeAprovada.frequencia ?? `${i.parametrosGradeAprovada.diasSemana.length}x por semana`} · ${i.parametrosGradeAprovada.diasSemana.map((d) => nomeDia[d]).join(", ")}.` : ""}{i.pendencias.length ? ` Pendências: ${i.pendencias.join(" ")}` : ""}</span></li>)}</ul><label className="block">Motivo<input className="ml-2 w-96 rounded border px-2 py-1" value={motivo} onChange={(e) => setMotivo(e.target.value)} /></label><FeedbackAcao erro={acao.erro} /><button className={botaoClasses({ tamanho: "lg" })} disabled={previaAcao.ocupado || acao.ocupado || motivo.trim().length < 5} onClick={() => salvar(previa)}>{acao.ocupado ? "Preparando…" : "Preparar revisão conjunta"}</button></>}</section>;
}
