CREATE OR REPLACE FUNCTION "conferir_material_quantidade_aulas_179"() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE p "PropostaQuantidadeAulasModalidade"%ROWTYPE; total_snapshot INTEGER; total_turmas_snapshot INTEGER; total_impactos INTEGER; divergente BOOLEAN; agenda_ausente BOOLEAN; agenda_excedente BOOLEAN; historico_alterado BOOLEAN;
BEGIN
  SELECT * INTO p FROM "PropostaQuantidadeAulasModalidade" WHERE id=NEW."propostaId";
  IF jsonb_typeof(p.snapshot->'impactos') IS DISTINCT FROM 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p.snapshot->'impactos') s WHERE jsonb_typeof(s->'agendaAntes') IS DISTINCT FROM 'array' OR jsonb_typeof(s->'agendaDepois') IS DISTINCT FROM 'array' OR jsonb_typeof(s->'excecoesQ37') IS DISTINCT FROM 'array') THEN RAISE EXCEPTION 'Snapshot material incompleto'; END IF;
  IF p.situacao <> 'APLICADA' OR NOT EXISTS (SELECT 1 FROM "Modalidade" m WHERE m.id=p."modalidadeId" AND m."aulasPorNivel"=p."quantidadeNova") THEN RAISE EXCEPTION 'Aplicação sem meta material da modalidade'; END IF;
  SELECT jsonb_array_length(p.snapshot->'impactos'), count(DISTINCT s->>'turmaId'), (SELECT count(*) FROM "ImpactoQuantidadeAulasModalidade" WHERE "propostaId"=p.id) INTO total_snapshot, total_turmas_snapshot, total_impactos FROM jsonb_array_elements(p.snapshot->'impactos') s;
  IF total_snapshot <> total_turmas_snapshot OR total_snapshot <> total_impactos THEN RAISE EXCEPTION 'Aplicação sem bijeção completa de impactos'; END IF;
  SELECT EXISTS (SELECT 1 FROM jsonb_array_elements(p.snapshot->'impactos') s LEFT JOIN "ImpactoQuantidadeAulasModalidade" i ON i."propostaId"=p.id AND i."turmaId"=s->>'turmaId' WHERE i.id IS NULL OR i.alcance::text IS DISTINCT FROM s->>'alcance' OR i."quantidadeAnterior" <> (s->>'quantidadeAnterior')::int OR i."quantidadeNova" <> (s->>'quantidadeNova')::int OR i.publicada IS DISTINCT FROM (s->>'publicada')::boolean OR i."excecoesQ37" IS DISTINCT FROM s->'excecoesQ37') INTO divergente;
  IF divergente THEN RAISE EXCEPTION 'Aplicação diverge do impacto conferido'; END IF;
  SELECT EXISTS (SELECT 1 FROM jsonb_array_elements(p.snapshot->'impactos') s, jsonb_array_elements(s->'agendaDepois') a WHERE (s->>'publicada')::boolean AND NOT EXISTS (SELECT 1 FROM "EncontroAgenda" e WHERE e."turmaId"=s->>'turmaId' AND e.inicio=((a->>'inicio')::timestamptz AT TIME ZONE 'UTC') AND e.fim=((a->>'fim')::timestamptz AT TIME ZONE 'UTC') AND e.status::text=a->>'status' AND e."professorId" IS NOT DISTINCT FROM a->>'professorId' AND e."propostaGradeId" IS NOT DISTINCT FROM a->>'propostaGradeId' AND (a->>'id' IS NULL OR e.id=a->>'id'))) INTO agenda_ausente;
  IF agenda_ausente THEN RAISE EXCEPTION 'Aplicação não materializou a agenda conferida'; END IF;
  SELECT EXISTS (SELECT 1 FROM jsonb_array_elements(p.snapshot->'impactos') s WHERE (s->>'publicada')::boolean AND (SELECT count(*) FROM "EncontroAgenda" e WHERE e."turmaId"=s->>'turmaId') <> jsonb_array_length(s->'agendaDepois')) INTO agenda_excedente;
  IF agenda_excedente THEN RAISE EXCEPTION 'Aplicação possui encontro fora da agenda conferida'; END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(p.snapshot->'impactos') s WHERE (s->>'publicada')::boolean IS FALSE AND NOT EXISTS (SELECT 1 FROM "PropostaGradeTurma" nova JOIN "PropostaGradeTurma" origem ON origem.id=s->>'propostaGradeId' WHERE nova."turmaId"=s->>'turmaId' AND nova."calendarioId"=origem."calendarioId" AND nova."chaveIdempotencia"=('quantidade-rascunho:' || p.id || ':' || (s->>'turmaId')) AND nova.snapshot->'origem'->>'quantidadeAulas'=s->>'quantidadeNova' AND jsonb_typeof(nova.snapshot->'grade'->'encontros')='array' AND jsonb_array_length(nova.snapshot->'grade'->'encontros')=jsonb_array_length(s->'agendaDepois') AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(s->'agendaDepois') a WHERE NOT EXISTS (SELECT 1 FROM jsonb_array_elements(nova.snapshot->'grade'->'encontros') e WHERE e->>'inicio'=a->>'inicio' AND e->>'fim'=a->>'fim')))) THEN RAISE EXCEPTION 'Rascunho não materializou nova versão de grade conferida'; END IF;
  SELECT EXISTS (SELECT 1 FROM jsonb_array_elements(p.snapshot->'impactos') s, jsonb_array_elements(s->'agendaAntes') a WHERE (((a->>'inicio')::timestamptz AT TIME ZONE 'UTC') <= NEW."aplicadaEm" OR a->>'status' IN ('MINISTRADO','NAO_REALIZADO','IMPEDIDO_ESCOLA','CANCELADO')) AND NOT EXISTS (SELECT 1 FROM "EncontroAgenda" e WHERE e.id=a->>'id' AND e."turmaId"=s->>'turmaId' AND e.inicio=((a->>'inicio')::timestamptz AT TIME ZONE 'UTC') AND e.fim=((a->>'fim')::timestamptz AT TIME ZONE 'UTC') AND e.status::text=a->>'status' AND e."professorId" IS NOT DISTINCT FROM a->>'professorId' AND e."propostaGradeId" IS NOT DISTINCT FROM a->>'propostaGradeId')) INTO historico_alterado;
  IF historico_alterado THEN RAISE EXCEPTION 'Aplicação alterou encontro histórico ou diário preservado'; END IF;
  RETURN NEW;
END $$;
