-- M01: preparação rastreável. Não cria alunos, matrículas, cobranças ou presença.
CREATE TYPE "EstadoLotePreparacaoMigracao" AS ENUM ('PREPARADO', 'COM_PENDENCIAS');
CREATE TYPE "EstadoLinhaPreparacaoMigracao" AS ENUM ('PRONTA_PARA_REVISAO', 'COM_PENDENCIAS', 'COLISAO_ORIGEM');
CREATE TABLE "LotePreparacaoMigracao" (  id TEXT NOT NULL,  origem TEXT NOT NULL,  "chaveLote" TEXT NOT NULL,  "entradaHash" TEXT NOT NULL,  estado "EstadoLotePreparacaoMigracao" NOT NULL,  "preparadoPorId" TEXT NOT NULL,  "criadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  "atualizadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  CONSTRAINT "LotePreparacaoMigracao_pkey" PRIMARY KEY (id),  CONSTRAINT "LotePreparacaoMigracao_preparadoPorId_fkey" FOREIGN KEY ("preparadoPorId") REFERENCES "Usuario"(id) ON DELETE RESTRICT ON UPDATE NO ACTION);
CREATE UNIQUE INDEX "LotePreparacaoMigracao_origem_chave_key" ON "LotePreparacaoMigracao"(origem, "chaveLote");
CREATE INDEX "LotePreparacaoMigracao_estado_criado_idx" ON "LotePreparacaoMigracao"(estado, "criadoEm");
CREATE TABLE "LinhaPreparacaoMigracao" (  id TEXT NOT NULL,  "loteId" TEXT NOT NULL,  "linhaOrigem" TEXT NOT NULL,  "alunoOrigemId" TEXT,  "turmaOrigemId" TEXT,  "matriculaOrigemId" TEXT,  "financeiroOrigemId" TEXT,  "dadosOrigem" JSONB NOT NULL,  "entradaHash" TEXT NOT NULL,  estado "EstadoLinhaPreparacaoMigracao" NOT NULL,  "criadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  CONSTRAINT "LinhaPreparacaoMigracao_pkey" PRIMARY KEY (id),  CONSTRAINT "LinhaPreparacaoMigracao_loteId_fkey" FOREIGN KEY ("loteId") REFERENCES "LotePreparacaoMigracao"(id) ON DELETE RESTRICT ON UPDATE NO ACTION);
CREATE UNIQUE INDEX "LinhaPreparacaoMigracao_lote_linha_key" ON "LinhaPreparacaoMigracao"("loteId", "linhaOrigem");
CREATE INDEX "LinhaPreparacaoMigracao_aluno_origem_idx" ON "LinhaPreparacaoMigracao"("alunoOrigemId");
CREATE INDEX "LinhaPreparacaoMigracao_turma_origem_idx" ON "LinhaPreparacaoMigracao"("turmaOrigemId");
CREATE INDEX "LinhaPreparacaoMigracao_matricula_origem_idx" ON "LinhaPreparacaoMigracao"("matriculaOrigemId");
CREATE INDEX "LinhaPreparacaoMigracao_financeiro_origem_idx" ON "LinhaPreparacaoMigracao"("financeiroOrigemId");
CREATE TABLE "PendenciaCampoPreparacaoMigracao" (  id TEXT NOT NULL,  "linhaId" TEXT NOT NULL,  campo TEXT NOT NULL,  codigo TEXT NOT NULL,  detalhe TEXT NOT NULL,  "criadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  CONSTRAINT "PendenciaCampoPreparacaoMigracao_pkey" PRIMARY KEY (id),  CONSTRAINT "PendenciaCampoPreparacaoMigracao_linhaId_fkey" FOREIGN KEY ("linhaId") REFERENCES "LinhaPreparacaoMigracao"(id) ON DELETE RESTRICT ON UPDATE NO ACTION);
CREATE UNIQUE INDEX "PendenciaCampoPreparacaoMigracao_linha_campo_codigo_key" ON "PendenciaCampoPreparacaoMigracao"("linhaId", campo, codigo);
CREATE INDEX "PendenciaCampoPreparacaoMigracao_campo_idx" ON "PendenciaCampoPreparacaoMigracao"(campo);
CREATE TABLE "ColisaoOrigemPreparacaoMigracao" (  id TEXT NOT NULL,  tipo TEXT NOT NULL,  "identificadorOrigem" TEXT NOT NULL,  "linhaExistenteId" TEXT NOT NULL,  "linhaConflitanteId" TEXT NOT NULL,  "criadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  CONSTRAINT "ColisaoOrigemPreparacaoMigracao_pkey" PRIMARY KEY (id),  CONSTRAINT "ColisaoOrigemPreparacaoMigracao_existente_fkey" FOREIGN KEY ("linhaExistenteId") REFERENCES "LinhaPreparacaoMigracao"(id) ON DELETE RESTRICT ON UPDATE NO ACTION,  CONSTRAINT "ColisaoOrigemPreparacaoMigracao_conflitante_fkey" FOREIGN KEY ("linhaConflitanteId") REFERENCES "LinhaPreparacaoMigracao"(id) ON DELETE RESTRICT ON UPDATE NO ACTION);
CREATE UNIQUE INDEX "ColisaoOrigemPreparacaoMigracao_conflitante_tipo_id_key" ON "ColisaoOrigemPreparacaoMigracao"("linhaConflitanteId", tipo, "identificadorOrigem");
CREATE INDEX "ColisaoOrigemPreparacaoMigracao_tipo_id_idx" ON "ColisaoOrigemPreparacaoMigracao"(tipo, "identificadorOrigem");
CREATE FUNCTION "proteger_linha_preparacao_migracao_155"() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN  IF NEW."loteId" IS DISTINCT FROM OLD."loteId"     OR NEW."linhaOrigem" IS DISTINCT FROM OLD."linhaOrigem"     OR NEW."alunoOrigemId" IS DISTINCT FROM OLD."alunoOrigemId"     OR NEW."turmaOrigemId" IS DISTINCT FROM OLD."turmaOrigemId"     OR NEW."matriculaOrigemId" IS DISTINCT FROM OLD."matriculaOrigemId"     OR NEW."financeiroOrigemId" IS DISTINCT FROM OLD."financeiroOrigemId"     OR NEW."dadosOrigem" IS DISTINCT FROM OLD."dadosOrigem"     OR NEW."entradaHash" IS DISTINCT FROM OLD."entradaHash" THEN    RAISE EXCEPTION 'Linha de preparação de migração é imutável';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER "LinhaPreparacaoMigracao_imutavel_155"  BEFORE UPDATE ON "LinhaPreparacaoMigracao"  FOR EACH ROW EXECUTE FUNCTION "proteger_linha_preparacao_migracao_155"();
CREATE FUNCTION "atualizar_lote_preparacao_migracao_155"() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN  NEW."atualizadoEm" = CURRENT_TIMESTAMP;
  RETURN NEW;
END $$;
CREATE TRIGGER "LotePreparacaoMigracao_atualizado_155"  BEFORE UPDATE ON "LotePreparacaoMigracao"  FOR EACH ROW EXECUTE FUNCTION "atualizar_lote_preparacao_migracao_155"();
CREATE TABLE "ConflitoLinhaPreparacaoMigracao" (  id TEXT NOT NULL,  "loteId" TEXT NOT NULL,  "linhaOrigem" TEXT NOT NULL,  "entradaHash" TEXT NOT NULL,  codigo TEXT NOT NULL,  "dadosConflitantes" JSONB NOT NULL,  "criadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,  CONSTRAINT "ConflitoLinhaPreparacaoMigracao_pkey" PRIMARY KEY (id),  CONSTRAINT "ConflitoLinhaPreparacaoMigracao_loteId_fkey" FOREIGN KEY ("loteId") REFERENCES "LotePreparacaoMigracao"(id) ON DELETE RESTRICT ON UPDATE NO ACTION);
CREATE UNIQUE INDEX "ConflitoLinhaPreparacaoMigracao_lote_linha_hash_key" ON "ConflitoLinhaPreparacaoMigracao"("loteId", "linhaOrigem", "entradaHash");
CREATE INDEX "ConflitoLinhaPreparacaoMigracao_lote_criado_idx" ON "ConflitoLinhaPreparacaoMigracao"("loteId", "criadoEm");
