"use client";

import { useRef, useState, useTransition, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { decidirRegularizacaoFonteGravacao, proporRegularizacaoFonteGravacao } from "@/server/gravacoes/regularizacao-fonte";
import { formatarInstanteExibicao } from "@/server/operacao/fuso-exibicao";
import { MensagemStatus } from "@/components/MensagemStatus";
import { botaoClasses } from "@/components/Botao";

type Fonte = { id: string; rotulo: string; versao: number | null };
type Proposta = { id: string; destino: string; podeDecidir: boolean; alvo: string; arquivoOficialId: string; driveRevisionId: string; motivo: string; versaoEsperada: number; criadaEm: Date; preparador: { nome: string | null }; decisao: { aprovada: boolean; motivo: string; decididaEm: Date; decisor: { nome: string | null } } | null };

export function RegularizacoesGravacao({ fontes, propostas, fusoExibicao }: { fontes: Fonte[]; propostas: Proposta[]; fusoExibicao: string }) {
  const [ocupado, iniciar] = useTransition(); const [erro, setErro] = useState(""); const [feito, setFeito] = useState(""); const router = useRouter(); const chaves = useRef(new Map<string, string>());
  const executar = (acao: () => Promise<{ ok: boolean; erro?: string }>, sucesso: string) => iniciar(async () => { setErro(""); setFeito(""); try { const r = await acao(); if (!r.ok) setErro(r.erro ?? "A operação não foi confirmada."); else { setFeito(sucesso); router.refresh(); } } catch { setErro("A operação não foi confirmada. Atualize a página antes de tentar novamente."); } });
  function propor(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const alvo = String(f.get("alvo") ?? ""); const [tipo, alvoId] = alvo.split(":"); const arquivoOficialId = String(f.get("arquivo") ?? ""), motivo = String(f.get("motivo") ?? ""); const chave = `${alvo}|${arquivoOficialId}|${motivo}`; const chaveIdempotencia = chaves.current.get(chave) ?? crypto.randomUUID(); chaves.current.set(chave, chaveIdempotencia); executar(() => proporRegularizacaoFonteGravacao({ alvo: tipo, alvoId, arquivoOficialId, motivo, chaveIdempotencia }), "Proposta registrada para revisão independente."); }
  return <section className="space-y-6"><p className="text-sm text-gray-700">A reprodução usa apenas uma revisão já fixada. Arquivo legado ou alteração externa exige proposta e aprovação de outra pessoa; esta tela não abre o Drive nem revela links.</p>
    <form onSubmit={propor} className="space-y-3 rounded border bg-surface p-4"><h2 className="font-medium">Propor regularização de fonte</h2><label className="block text-sm">Publicação ou material<select name="alvo" required className="mt-1 block w-full rounded border p-2"><option value="">Selecione</option>{fontes.map((f) => <option key={f.id} value={f.id}>{f.rotulo}{f.versao == null ? " — sem revisão fixa" : ` — versão ${f.versao}`}</option>)}</select></label><label className="block text-sm">ID do arquivo institucional<input name="arquivo" required minLength={3} maxLength={500} className="mt-1 block w-full rounded border p-2" /></label><label className="block text-sm">Motivo<textarea name="motivo" required minLength={5} maxLength={4000} className="mt-1 block w-full rounded border p-2" /></label><button disabled={ocupado} className={botaoClasses({ variante: "secundario", tamanho: "lg" })}>Preparar proposta para revisão</button></form>
    <section className="space-y-3"><h2 className="font-medium">Propostas e decisões</h2>{propostas.length === 0 ? <p className="text-sm">Não há propostas de regularização.</p> : propostas.map((p) => <article key={p.id} className="rounded border bg-surface p-4 text-sm"><p className="font-medium">{p.destino}, versão esperada {p.versaoEsperada}</p><p className="mt-1">Arquivo institucional: {p.arquivoOficialId}. Revisão fixada: {p.driveRevisionId}.</p><p className="mt-1 whitespace-pre-wrap">Motivo: {p.motivo}</p><p className="mt-1 text-gray-600">Preparada por {p.preparador.nome ?? "Usuário"} em {formatarInstanteExibicao(p.criadaEm, fusoExibicao, "UTC").texto} ({fusoExibicao}).</p>{p.decisao ? <p role="status" className="mt-2">{p.decisao.aprovada ? "Aprovada" : "Rejeitada"} por {p.decisao.decisor.nome ?? "Usuário"}: {p.decisao.motivo}</p> : !p.podeDecidir ? <p role="status" className="mt-2">Aguardando decisão de outra pessoa autorizada.</p> : <form className="mt-3 space-y-2" onSubmit={(e) => { e.preventDefault(); const motivo = String(new FormData(e.currentTarget).get("motivo") ?? ""); executar(() => decidirRegularizacaoFonteGravacao({ propostaId: p.id, aprovar: String((e.nativeEvent as SubmitEvent).submitter?.getAttribute("value")) === "aprovar", motivo }), "Decisão registrada."); }}><label className="block">Motivo da decisão<textarea name="motivo" required minLength={5} maxLength={4000} className="block w-full rounded border p-2" /></label><button name="decisao" value="aprovar" disabled={ocupado} className={botaoClasses({ variante: "secundario", tamanho: "lg" })}>Aprovar fonte</button><button name="decisao" value="rejeitar" disabled={ocupado} className={`${botaoClasses({ variante: "secundario", tamanho: "lg" })} ml-2`}>Rejeitar</button></form>}</article>)}</section><MensagemStatus texto={feito} />{erro && <p role="alert" className="text-red-700">{erro}</p>}</section>;
}
