// Manifesto da trava de vazio paginado (src/app/vazio-paginado.test.ts): cada texto "nesta página" do
// código de produção que a paginação protege — arquivo | condição que o protege | texto. Trocar a
// condição (o cursor de outra lista, a página de outro painel) ou o texto muda o mapa; a mudança
// aparece no diff da revisão.
export const MAPA_VAZIO_PAGINADO: readonly string[] = [
  "src/app/(app)/academico/admissoes/[id]/page.tsx | r.pagina > 1 | Nenhuma versão nesta página.",
  "src/app/(app)/academico/calendario/[id]/revisoes/page.tsx | r.pagina > 1 | Nenhuma revisão nesta página.",
  "src/app/(app)/academico/equivalencias/page.tsx | pagina > 1 | Nenhuma proposta autorizada aguarda execução nesta página.",
  "src/app/(app)/academico/equivalencias/page.tsx | pagina > 1 | Nenhuma proposta de aproveitamento nesta página.",
  "src/app/(app)/academico/recuperacoes/[realizacaoId]/page.tsx | antesVersao | Nenhuma versão de nota registrada nesta página.",
  "src/app/(app)/academico/recuperacoes/correcoes/[notaId]/page.tsx | antesVersao | Sem propostas nesta página.",
  "src/app/(app)/academico/recuperacoes/designadas/page.tsx | pagina > 1 | Nenhuma tentativa disponível nesta página.",
  "src/app/(app)/academico/recuperacoes/page.tsx | pagina > 1 | Nenhuma realização disponível nesta página.",
  "src/app/(app)/academico/recuperacoes/planos/[propostaId]/page.tsx | pagina > 1 | Nenhuma reserva nesta página.",
  "src/app/(app)/academico/recuperacoes/planos/[propostaId]/prorrogacoes/page.tsx | antesVersao | Nenhuma proposta nesta página.",
  "src/app/(app)/academico/recuperacoes/planos/page.tsx | antesVersao | Nenhuma proposta nesta página.",
  "src/app/(app)/academico/recuperacoes/tentativas/[itemReservaId]/designacao/page.tsx | antesVersao | Nenhuma designação nesta página.",
  "src/app/(app)/academico/reposicoes/correcoes/[reposicaoId]/CorrecoesConclusaoReposicao.tsx | antesVersao | Não há correções nesta página.",
  "src/app/(app)/alunos/[id]/movimentacoes/page.tsx | pedidos.pagina > 1 | Nenhum pedido registrado nesta página.",
  "src/app/(app)/diario/page.tsx | antes | nesta página",
  "src/app/(app)/financeiro/acertos-cobertura/page.tsx | pagina > 1 | Nenhum aditivo de cobertura foi encontrado nesta página.",
  "src/app/(app)/financeiro/acertos-taxa/page.tsx | pagina > 1 | Nenhum aditivo com condições de taxa nesta página.",
  "src/app/(app)/financeiro/continuidade/FilaContinuidadeMensal.tsx | pagina > 1 | Nenhuma matrícula precisa de acompanhamento nesta página.",
  "src/app/(app)/financeiro/desistencias/page.tsx | pagina > 1 | Nenhum pedido nesta página.",
  "src/app/(app)/financeiro/migracao/page.tsx | pagina > 1 | Nenhuma linha financeira nesta página.",
  "src/app/(app)/financeiro/permuta/page.tsx | pagina > 1 | Nenhum acordo nesta página.",
  "src/app/(app)/financeiro/recebimentos/page.tsx | pagina > 1 | Nenhum recebimento nesta página.",
  "src/app/(app)/leads/[id]/contratacao/page.tsx | c.pagina > 1 | Nenhum cadastro nesta página. Consulte as demais páginas ou confira a identidade com a Secretaria.",
  "src/app/(app)/matriculas/[id]/contrato/aditivos/OriginaisPainel.tsx | pagina > 1 | Nenhum original nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/aditivos/ParticipantesFormulario.tsx | formulario.paginaDocumentos > 1 | Nenhum documento disponível nesta página. Cadastre as evidências na documentação da matrícula antes de concluir.",
  "src/app/(app)/matriculas/[id]/contrato/aditivos/ParticipantesHistorico.tsx | pagina > 1 | Nenhuma conferência nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/aditivos/[propostaId]/originais/[artefatoId]/page.tsx | pagina > 1 | Nenhum registro nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/aditivos/page.tsx | d.pagina > 1 | Nenhuma proposta nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/aditivos/page.tsx | d.paginaModelos > 1 | Nenhum modelo de aditivo aprovado está disponível nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/page.tsx | d.paginaHistorico > 1 | Nenhuma prévia registrada nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/page.tsx | d.paginaModelos > 1 | Nenhum modelo publicado disponível nesta página para o regime da matrícula.",
  "src/app/(app)/matriculas/[id]/contrato/previas/[previaId]/participantes/page.tsx | pagina > 1 | Nenhuma conferência registrada nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/substituicoes/Andamento.tsx | dados.pagina > 1 | Nenhum retorno nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/substituicoes/page.tsx | d.pagina > 1 | Nenhuma proposta nesta página.",
  "src/app/(app)/matriculas/[id]/contrato/substituicoes/page.tsx | d.paginaConferencias > 1 | Nenhuma conferência de outro original nesta página. Prepare e confira o documento substituto nos documentos da matrícula.",
  "src/app/(app)/matriculas/[id]/fechamentos-horas/page.tsx | q.cursor | Nenhum rascunho salvo nesta página.",
  "src/app/(app)/matriculas/[id]/indisponibilidade-oferta/RelatosIndisponibilidadeOferta.tsx | d.pagina > 1 | Nenhum relato registrado nesta página.",
  "src/app/(app)/matriculas/[id]/indisponibilidade-oferta/[registroId]/termino/TerminoIndisponibilidadeOferta.tsx | d.pagina > 1 | Nenhuma proposta registrada nesta página.",
  "src/app/(app)/matriculas/[id]/ocorrencias-financeiras/page.tsx | cursor | Nenhum encontro particular nesta página.",
  "src/app/(app)/matriculas/[id]/pagador/page.tsx | pagina > 1 | Nenhum registro nesta página.",
  "src/app/(app)/matriculas/[id]/reserva/page.tsx | r.pagina > 1 | Nenhuma turma nesta página.",
  "src/app/(app)/secretaria/avisos-agenda/page.tsx | pagina > 1 | Nenhum aviso nesta página.",
  "src/app/(app)/secretaria/avisos-agenda/page.tsx | paginaPendencias > 1 | Nenhuma pendência nesta página.",
  "src/app/(app)/secretaria/desistencias/page.tsx | pagina > 1 | Nenhum pedido pendente nesta página.",
  "src/app/(app)/secretaria/envios-portal/page.tsx | pagina > 1 | Nenhuma solicitação nesta página.",
];
