import { beforeEach, expect, it, vi } from "vitest";
import { Papel } from "@prisma/client";
const { authMock } = vi.hoisted(() => ({ authMock: vi.fn() }));
vi.mock("@/lib/auth", () => ({ auth: authMock }));
import { prisma } from "@/lib/prisma";
import { criarUsuario, seedCatalogoMinimo, truncarBanco } from "@/test/integracao";
import { regraAvaliacaoTeste } from "@/test/regra-avaliacao";
import { decidirRegraAvaliacaoTx, prepararRegraAvaliacaoTx } from "./regras-tx";
import { decidirConferenciaRegraHistorica, proporConferenciaRegraHistorica, revisarConferenciaRegraHistorica } from "./conferencia-regra-historica";

let preparador: string, decisor: string, turmaId: string, regraHistoricaId: string;
const entrar = (id: string) => authMock.mockResolvedValue({ user: { id } });
async function publicar(versao: number) { const nivelId=(await prisma.turma.findUniqueOrThrow({where:{id:turmaId}})).nivelId; const conteudo=regraAvaliacaoTeste(); conteudo.titulo=`Regra histórica ${versao}`; const proposta=await prisma.$transaction(tx=>prepararRegraAvaliacaoTx(tx,preparador,{nivelId,versaoEsperada:versao-1,conteudo,motivo:"Versão institucional publicada",chaveIdempotencia:`historica-${versao}`})); const regra=await prisma.versaoRegraAvaliacao.findUniqueOrThrow({where:{id:proposta.id}}); await prisma.$transaction(tx=>decidirRegraAvaliacaoTx(tx,decisor,{regraId:regra.id,conteudoHash:regra.conteudoHash,aprovada:true,motivo:"Publicação independente"})); return regra.id; }
beforeEach(async()=>{ await truncarBanco(); const catalogo=await seedCatalogoMinimo(); preparador=(await criarUsuario([Papel.GERENTE_PEDAGOGICO])).id; decisor=(await criarUsuario([Papel.ADMINISTRADOR])).id; const nivel=await prisma.nivel.create({data:{idiomaId:catalogo.idioma.id,codigo:"HIST",ordem:1}}); turmaId=(await prisma.turma.create({data:{modalidadeId:catalogo.modalidade.id,nivelId:nivel.id,status:"EM_ANDAMENTO",dataInicio:new Date("2025-01-01T00:00:00Z")}})).id; entrar(preparador); regraHistoricaId=await publicar(1); await publicar(2); entrar(preparador); });
async function preparar() { const revisao=await revisarConferenciaRegraHistorica({turmaId,destinoId:regraHistoricaId}); expect(revisao.ok).toBe(true); if(!revisao.ok||!revisao.dado) throw new Error("Revisão ausente"); const input={turmaId,destinoId:regraHistoricaId,estadoHash:revisao.dado.estadoHash,versaoEsperada:revisao.dado.versaoEsperada,motivo:"Conferência do material histórico",evidencia:"Ata pedagógica arquivada confirma estes critérios",chaveIdempotencia:"conferencia-historica-1"}; const proposta=await proporConferenciaRegraHistorica(input); expect(proposta.ok).toBe(true); if(!proposta.ok||!proposta.dado) throw new Error("Proposta ausente"); return {input,id:proposta.dado.id,estadoHash:revisao.dado.estadoHash}; }
it("vincula versão publicada histórica escolhida por evidência após decisão independente e repete somente a mesma decisão",async()=>{ const p=await preparar(); expect(await proporConferenciaRegraHistorica(p.input)).toMatchObject({ok:true,dado:{id:p.id}}); expect((await decidirConferenciaRegraHistorica({propostaId:p.id,estadoHash:p.estadoHash,aprovada:true,motivo:"Conferência independente"})).ok).toBe(false); entrar(decisor); const entrada={propostaId:p.id,estadoHash:p.estadoHash,aprovada:true,motivo:"Conferência independente"}; expect(await decidirConferenciaRegraHistorica(entrada)).toMatchObject({ok:true,dado:{aplicada:true}}); expect(await decidirConferenciaRegraHistorica(entrada)).toMatchObject({ok:true,dado:{aplicada:true}}); expect((await prisma.turma.findUniqueOrThrow({where:{id:turmaId}})).regraAvaliacaoId).toBe(regraHistoricaId); });
it("recusa regra não publicada, autoaprovação e aprovação após mudança",async()=>{ const nivelId=(await prisma.turma.findUniqueOrThrow({where:{id:turmaId}})).nivelId; const pendente=await prisma.$transaction(tx=>prepararRegraAvaliacaoTx(tx,preparador,{nivelId,versaoEsperada:2,conteudo:regraAvaliacaoTeste(),motivo:"Versão ainda pendente",chaveIdempotencia:"nao-publicada"})); expect((await revisarConferenciaRegraHistorica({turmaId,destinoId:pendente.id})).ok).toBe(false); const p=await preparar(); expect((await decidirConferenciaRegraHistorica({propostaId:p.id,estadoHash:p.estadoHash,aprovada:true,motivo:"Autoaprovação proibida"})).ok).toBe(false); await prisma.aluno.create({data:{primeiroNome:"Impede",paisId:(await prisma.pais.findFirstOrThrow()).id}}).then(async aluno=>prisma.alocacaoTurma.create({data:{turmaId,alunoId:aluno.id}})); entrar(decisor); expect((await decidirConferenciaRegraHistorica({propostaId:p.id,estadoHash:p.estadoHash,aprovada:true,motivo:"Mudou depois da revisão"})).ok).toBe(false); });
