"use server";
import { Papel } from "@prisma/client";
import { z } from "zod";
import { executarAcao, exigirSessaoComPapel, ErroRegra } from "@/server/_shared";
import { prisma } from "@/lib/prisma";
import { bloquearConferenciaRegraHistorica, contextoConferenciaRegraHistorica, DecidirConferenciaRegraHistoricaSchema, decidirConferenciaRegraHistoricaTx, ProporConferenciaRegraHistoricaSchema, proporConferenciaRegraHistoricaTx, RevisarConferenciaRegraHistoricaSchema } from "./conferencia-regra-historica-tx";

export async function revisarConferenciaRegraHistorica(input: z.input<typeof RevisarConferenciaRegraHistoricaSchema>) { return executarAcao(async () => { const u = await exigirSessaoComPapel(Papel.GERENTE_PEDAGOGICO), d = RevisarConferenciaRegraHistoricaSchema.parse(input); return prisma.$transaction(async tx => { await bloquearConferenciaRegraHistorica(tx, d.turmaId, u.id); const c = await contextoConferenciaRegraHistorica(tx, d.turmaId, d.destinoId); const ultima = await tx.propostaConferenciaRegraHistoricaTurma.findFirst({ where: { turmaId: d.turmaId }, orderBy: { versao: "desc" }, select: { versao: true } }); return { estadoHash: c.estadoHash, versaoEsperada: ultima?.versao ?? 0, turma: c.snapshot.turma, destino: c.snapshot.destino, encontros: c.snapshot.encontros.length, diarios: c.snapshot.diarios.length, alocacoes: c.snapshot.alocacoes.length }; }); }); }
export async function proporConferenciaRegraHistorica(input: z.input<typeof ProporConferenciaRegraHistoricaSchema>) { return executarAcao(async () => { const u = await exigirSessaoComPapel(Papel.GERENTE_PEDAGOGICO); return prisma.$transaction(tx => proporConferenciaRegraHistoricaTx(tx, u.id, input)); }); }
export async function decidirConferenciaRegraHistorica(input: z.input<typeof DecidirConferenciaRegraHistoricaSchema>) { return executarAcao(async () => { const u = await exigirSessaoComPapel(Papel.GERENTE_PEDAGOGICO); return prisma.$transaction(tx => decidirConferenciaRegraHistoricaTx(tx, u.id, input)); }); }

export async function consultarConferenciasRegraHistorica(input: { turmaId: string; pagina?: number }) { return executarAcao(async () => { const u = await exigirSessaoComPapel(Papel.GERENTE_PEDAGOGICO); const d = z.object({ turmaId: RevisarConferenciaRegraHistoricaSchema.shape.turmaId, pagina: z.number().int().min(1).max(100000).default(1) }).strict().parse(input); return prisma.$transaction(async tx => { await bloquearConferenciaRegraHistorica(tx, d.turmaId, u.id); const [itens,ultima] = await Promise.all([tx.propostaConferenciaRegraHistoricaTurma.findMany({ where: { turmaId: d.turmaId }, orderBy: { versao: "desc" }, take: 21, skip: (d.pagina - 1) * 20, select: { id: true, versao: true, estadoHash: true, motivo: true, evidencia: true, criadaEm: true, snapshot: true, preparador: { select: { id: true, nome: true } }, destino: { select: { id: true, versao: true, conteudo: true, conteudoHash: true } }, decisao: { select: { id: true, aprovada: true, motivo: true, criadaEm: true, decisor: { select: { id: true, nome: true } } } } } }),tx.propostaConferenciaRegraHistoricaTurma.findFirst({where:{turmaId:d.turmaId},orderBy:{versao:"desc"},select:{id:true}})]); return { pagina: d.pagina, temProxima: itens.length > 20, itens: itens.slice(0,20).map(p => ({ ...p, podeDecidir: !p.decisao && p.preparador.id !== u.id, podeAprovar: !p.decisao && p.preparador.id !== u.id && p.id === ultima?.id })) }; }); }); }

/** A apresentação usa esta consulta; o submit sempre chama revisar novamente. */
export async function consultarPreparacaoConferenciaRegraHistorica(input: { turmaId: string }) { return executarAcao(async () => { const u = await exigirSessaoComPapel(Papel.GERENTE_PEDAGOGICO); const d = z.object({ turmaId: RevisarConferenciaRegraHistoricaSchema.shape.turmaId }).strict().parse(input); return prisma.$transaction(async tx => { await bloquearConferenciaRegraHistorica(tx,d.turmaId,u.id); const turma = await tx.turma.findUniqueOrThrow({ where:{id:d.turmaId}, select:{id:true,nome:true,codigo:true,nivelId:true,regraAvaliacaoId:true,nivel:{select:{codigo:true,idioma:{select:{nome:true}}}}} }); if(turma.regraAvaliacaoId) return {turma,destinos:[],pendencia:"A turma já possui regra vinculada."}; if(await tx.registroAvaliacaoMatricula.count({where:{turmaId:turma.id}})) return {turma,destinos:[],pendencia:"A turma possui avaliações registradas; preserve o histórico."}; const destinos=await tx.versaoRegraAvaliacao.findMany({where:{nivelId:turma.nivelId,decisao:{aprovada:true}},orderBy:{versao:"desc"},select:{id:true,versao:true,conteudo:true,conteudoHash:true}}); return {turma,destinos,pendencia:destinos.length?null:"Não existe versão publicada para este nível."}; }); }); }
