"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { decidirConferenciaRegraHistorica, proporConferenciaRegraHistorica, revisarConferenciaRegraHistorica } from "@/server/avaliacoes/conferencia-regra-historica";

export function ProporConferenciaRegraHistorica({ turmaId, destinoId, estadoHash, versaoEsperada }: { turmaId:string; destinoId:string; estadoHash:string; versaoEsperada:number }) {
 const router=useRouter(), chave=useRef<string|null>(null); const [ocupado,setOcupado]=useState(false),[mensagem,setMensagem]=useState("");
 return <form className="space-y-3" onChange={()=>{chave.current=null;setMensagem("")}} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);chave.current??=crypto.randomUUID();setOcupado(true);try{const r=await proporConferenciaRegraHistorica({turmaId,destinoId,estadoHash,versaoEsperada,motivo:String(f.get("motivo")??""),evidencia:String(f.get("evidencia")??""),chaveIdempotencia:chave.current});setMensagem(r.ok?"Conferência registrada para decisão independente.":r.erro);if(r.ok)router.refresh()}catch{setMensagem("O resultado não foi confirmado. Reenvie os mesmos dados.")}finally{setOcupado(false)}}}>
  <fieldset disabled={ocupado} className="space-y-3"><legend className="font-medium">Conferir regra histórica</legend><p>Selecione a versão que a evidência demonstra ter sido aplicada; esta decisão não altera notas, agenda ou frequência.</p><label className="block">Motivo<textarea name="motivo" required minLength={5} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="block">Evidência de que esta versão representa os critérios da turma<textarea name="evidencia" required minLength={5} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="block"><input type="checkbox" required/> Conferi a turma, a versão publicada e a evidência.</label><button className="rounded bg-brand-700 px-4 py-2 text-white">{ocupado?"Registrando…":"Registrar conferência"}</button></fieldset>{mensagem&&<p role="status">{mensagem}</p>}
 </form>;
}
export function PrepararConferenciaRegraHistorica({turmaId,destinos}:{turmaId:string;destinos:{id:string;versao:number}[]}){const[revisao,setRevisao]=useState<{destinoId:string;estadoHash:string;versaoEsperada:number}|null>(null),[mensagem,setMensagem]=useState(""),[ocupado,setOcupado]=useState(false);return <section className="space-y-3"><h2 className="text-xl font-medium">Conferência inicial da regra histórica</h2><p>Escolha a versão publicada que a evidência demonstra ter sido aplicada. A seleção não presume a versão mais recente.</p><form onSubmit={async e=>{e.preventDefault();const destinoId=String(new FormData(e.currentTarget).get("destinoId")??"");setOcupado(true);setMensagem("");try{const r=await revisarConferenciaRegraHistorica({turmaId,destinoId});if(!r.ok)setMensagem(r.erro);else if(r.dado)setRevisao({destinoId,estadoHash:r.dado.estadoHash,versaoEsperada:r.dado.versaoEsperada});}catch{setMensagem("A revisão não foi confirmada.")}finally{setOcupado(false)}}}><fieldset disabled={ocupado} className="flex gap-3"><label>Versão publicada<select name="destinoId" className="ml-2 rounded border p-2">{destinos.map(d=><option key={d.id} value={d.id}>Versão {d.versao}</option>)}</select></label><button className="rounded border px-3">{ocupado?"Revisando…":"Revisar"}</button></fieldset></form>{mensagem&&<p role="status">{mensagem}</p>}{revisao&&<ProporConferenciaRegraHistorica turmaId={turmaId} destinoId={revisao.destinoId} estadoHash={revisao.estadoHash} versaoEsperada={revisao.versaoEsperada}/>}</section>}
export function DecidirConferenciaRegraHistorica({propostaId,estadoHash,podeAprovar}:{propostaId:string;estadoHash:string;podeAprovar:boolean}){const router=useRouter();const[ocupado,setOcupado]=useState(false),[mensagem,setMensagem]=useState("");return <form className="space-y-3" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setOcupado(true);try{const r=await decidirConferenciaRegraHistorica({propostaId,estadoHash,aprovada:f.get("decisao")==="aprovar",motivo:String(f.get("motivo")??"")});setMensagem(r.ok?(r.dado?.aplicada?"Regra histórica conferida e vinculada.":"Conferência rejeitada."):r.erro);if(r.ok)router.refresh()}catch{setMensagem("O resultado não foi confirmado. Reenvie a mesma decisão.")}finally{setOcupado(false)}}}><fieldset disabled={ocupado} className="space-y-3"><label className="block">Decisão<select name="decisao" defaultValue="" required className="block rounded border p-2"><option value="">Selecione</option>{podeAprovar&&<option value="aprovar">Aprovar e vincular a regra</option>}<option value="rejeitar">Rejeitar</option></select></label><label className="block">Justificativa<textarea name="motivo" required minLength={5} maxLength={2000} className="block w-full rounded border p-2"/></label><label className="block"><input type="checkbox" required/> Conferi a proposta e a evidência.</label><button className="rounded border px-4 py-2">{ocupado?"Registrando…":"Registrar decisão"}</button></fieldset>{mensagem&&<p role="status">{mensagem}</p>}</form>}
