import Link from "next/link";
import { Papel } from "@prisma/client";
import { exigirSessaoPagina } from "@/server/_shared";
import { consultarConferenciasRegraHistorica, consultarPreparacaoConferenciaRegraHistorica } from "@/server/avaliacoes/conferencia-regra-historica";
import { ResumoRegra, type ConteudoRegra } from "../../../[nivelId]/ResumoRegra";
import { DecidirConferenciaRegraHistorica, PrepararConferenciaRegraHistorica } from "./ConferenciaRegraHistorica";

type Fotografia = { turma: { nome: string|null; codigo:string|null; status:string; dataInicio:string|null; dataFim:string|null }; destino: { versao:number; conteudo:ConteudoRegra; conteudoHash:string }; encontros: unknown[]; diarios: unknown[]; alocacoes: unknown[] };
function foto(valor: unknown): Fotografia | null { if(!valor || typeof valor!=="object") return null; const r=valor as Partial<Fotografia>; return r.turma&&r.destino&&Array.isArray(r.encontros)&&Array.isArray(r.diarios)&&Array.isArray(r.alocacoes)?r as Fotografia:null; }
function Registro({item}:{item:{versao:number;motivo:string;evidencia:string;criadaEm:Date;snapshot:unknown;preparador:{nome:string};decisao:{aprovada:boolean;motivo:string;criadaEm:Date;decisor:{nome:string}}|null;id:string;estadoHash:string;podeDecidir:boolean;podeAprovar:boolean}}){const s=foto(item.snapshot);return <article className="space-y-3 rounded border p-4"><h3 className="text-lg font-medium">Conferência {item.versao} — {item.decisao?(item.decisao.aprovada?"Aplicada":"Rejeitada"):"Aguardando decisão"}</h3><p>Preparada por {item.preparador.nome} em {item.criadaEm.toLocaleString("pt-BR",{timeZone:"UTC"})} UTC.</p><p className="whitespace-pre-wrap"><strong>Motivo:</strong> {item.motivo}</p><p className="whitespace-pre-wrap"><strong>Evidência:</strong> {item.evidencia}</p>{s?<section className="space-y-2 rounded bg-slate-50 p-3"><h4 className="font-medium">Fotografia conferida</h4><p>Turma {s.turma.nome??s.turma.codigo??"sem identificação"} · {s.turma.status}; início {s.turma.dataInicio??"não informado"}.</p><p>Versão preservada: {s.destino.versao}; {s.encontros.length} encontros, {s.diarios.length} diários e {s.alocacoes.length} alocações no momento da proposta.</p><ResumoRegra conteudo={s.destino.conteudo}/></section>:<p role="alert">Fotografia histórica indisponível para apresentação.</p>}{item.decisao?<p>Decisão de {item.decisao.decisor.nome} em {item.decisao.criadaEm.toLocaleString("pt-BR",{timeZone:"UTC"})} UTC: {item.decisao.motivo}</p>:item.podeDecidir?<DecidirConferenciaRegraHistorica propostaId={item.id} estadoHash={item.estadoHash} podeAprovar={item.podeAprovar}/>:<p role="status">Outra pessoa autorizada precisa registrar a decisão.</p>}</article>}

export default async function ConferenciaRegraHistoricaPage({params,searchParams}:{params:Promise<{turmaId:string}>;searchParams:Promise<{pagina?:string}>}){await exigirSessaoPagina(Papel.GERENTE_PEDAGOGICO);const{turmaId}=await params,p=Number((await searchParams).pagina??1);const[preparacao,historico]=await Promise.all([consultarPreparacaoConferenciaRegraHistorica({turmaId}),consultarConferenciasRegraHistorica({turmaId,pagina:Number.isInteger(p)&&p>0&&p<=100000?p:1})]);if(!preparacao.ok||!preparacao.dado)return <p role="alert">{preparacao.ok?"Preparação indisponível.":preparacao.erro}</p>;if(!historico.ok||!historico.dado)return <p role="alert">{historico.ok?"Histórico indisponível.":historico.erro}</p>;const d=preparacao.dado,h=historico.dado;return <section className="space-y-6"><nav className="flex gap-4"><Link className="underline" href="/configuracao/turmas">Turmas</Link><Link className="underline" href={`/academico/regras/${d.turma.nivelId}`}>Regras do nível</Link></nav><h1 className="text-2xl font-medium">Conferência da regra histórica</h1><p>{d.turma.nivel.idioma.nome} — {d.turma.nivel.codigo}. {d.turma.regraAvaliacaoId?"A regra já foi vinculada; o histórico permanece disponível.":"A turma não possui regra vinculada."}</p>{d.pendencia?<p role="status" className="rounded border p-3">{d.pendencia}</p>:<PrepararConferenciaRegraHistorica turmaId={turmaId} destinos={d.destinos.map(r=>({id:r.id,versao:r.versao}))}/>}<section className="space-y-4"><h2 className="text-xl font-medium">Histórico de conferências</h2>{!h.itens.length?<p>Nenhuma conferência registrada.</p>:h.itens.map(i=><Registro key={i.id} item={i}/>)}</section><nav aria-label="Páginas de conferências" className="flex gap-4">{h.pagina>1&&<Link href={`?pagina=${h.pagina-1}`}>Anterior</Link>}<span>Página {h.pagina}</span>{h.temProxima&&<Link href={`?pagina=${h.pagina+1}`}>Próxima</Link>}</nav></section>}
