"use server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { executarAcao, exigirSessaoComPapel, ErroRegra } from "@/server/_shared";
import { Papel } from "@prisma/client";
import { prepararProcessoAditivoTx } from "./aditivo-envio-tx";
const id = z.string().trim().min(1).max(100), destino = z.object({ fornecedor: z.enum(["ZAPSIGN", "CLICKSIGN", "DOCUSIGN"]), ambiente: z.enum(["SANDBOX", "PRODUCAO"]) });
const Preparar = destino.extend({ matriculaId: id, propostaId: id, artefatoId: id, conferenciaId: id }).strict();
export async function prepararProcessoAssinaturaAditivo(input: z.input<typeof Preparar>) { return executarAcao(async () => { const ator = await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA), d = Preparar.parse(input); return prisma.$transaction(tx => prepararProcessoAditivoTx(tx, ator.id, d), { timeout: 30000 }); }); }
export async function consultarProcessoAssinaturaAditivo(input: { matriculaId: string; propostaId: string; artefatoId: string; paginaTentativas?: number }) { return executarAcao(async () => { const ator = await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA); const d = z.object({ matriculaId: id, propostaId: id, artefatoId: id, paginaTentativas: z.number().int().min(1).max(100000).default(1) }).strict().parse(input); return prisma.$transaction(async tx => { const fresco = await tx.usuario.findUnique({ where: { id: ator.id }, select: { ativo: true, papeis: true } }); if (!fresco?.ativo || !fresco.papeis.some(p => p === Papel.SECRETARIA_ACADEMICA || p === Papel.ADMINISTRADOR)) throw new ErroRegra("Permissão de Secretaria necessária."); if (!await tx.artefatoAditivoContratual.count({ where: { id: d.artefatoId, propostaId: d.propostaId, proposta: { matriculaId: d.matriculaId } } })) throw new ErroRegra("Original indisponível nesta matrícula e proposta."); const p = await tx.processoAssinaturaAditivo.findFirst({ where: { propostaId: d.propostaId, artefatoId: d.artefatoId, proposta: { matriculaId: d.matriculaId } }, include: { tentativas: { orderBy: { numero: "desc" }, skip: (d.paginaTentativas - 1) * 20, take: 21, select: { numero: true, revisaoHash: true, iniciadaEm: true, observacoes: { take: 21, orderBy: { observadaEm: "desc" }, select: { resultado: true, referenciaExterna: true, observadaEm: true } } } } } }); if (!p) return null; return { id: p.id, propostaId: p.propostaId, artefatoId: p.artefatoId, conferenciaId: p.conferenciaId, fornecedor: p.fornecedor, ambiente: p.ambiente, estado: p.estado, tentativaAtual: p.tentativaAtual, referenciaExterna: p.referenciaExterna, criadoEm: p.criadoEm, paginaTentativas: d.paginaTentativas, temMaisTentativas: p.tentativas.length > 20, tentativas: p.tentativas.slice(0, 20).map(t => ({ ...t, temMaisObservacoes: t.observacoes.length > 20, observacoes: t.observacoes.slice(0, 20) })) }; }); }); }
