"use server";
import { Papel, Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { executarAcao, exigirSessaoComPapel, ErroPermissao, ErroRegra, registrarEvento } from "@/server/_shared";
import { hashSubstituicao } from "./substituicao-estado";
import { carregarEstadoConferenciaFinalAditivoTx } from "./aditivo-conferencia-final-estado";
import { calcularCreditoAcertoTaxa } from "./aditivo-acerto-taxa-calculo";
import { AplicarAcertoTaxaSchema, DecidirAcertoTaxaSchema, ProporAcertoTaxaSchema } from "./aditivo-acerto-taxa-acoes-schema";

async function financeiro(tx: Prisma.TransactionClient, id: string, aprovar = false) {
  const u = await tx.usuario.findUnique({ where: { id }, select: { ativo: true, papeis: true, permissoes: true } });
  if (!u?.ativo || !u.papeis.some(p => p === Papel.ADMINISTRADOR || p === Papel.FINANCEIRO) || (aprovar && !u.papeis.includes(Papel.ADMINISTRADOR) && !u.permissoes.includes("financeiro.aprovar_acertos"))) throw new ErroPermissao("Exige Financeiro ativo e permissão vigente.");
}
function foto(estado: { revisaoHash: string }, v: { id: string; condicoesHash: string }, c: { id: string; versao: number; moeda: string; valorNegociado: Prisma.Decimal; valorRecebido: Prisma.Decimal | null; valorLiquidadoCredito: Prisma.Decimal; vencimento: Date }, calc: ReturnType<typeof calcularCreditoAcertoTaxa>) {
 return { revisaoHash: estado.revisaoHash, condicoesHash: v.condicoesHash, versaoCondicoesId: v.id, cobranca: { id: c.id, versao: c.versao, moeda: c.moeda, valorNegociado: c.valorNegociado.toFixed(2), valorRecebido: c.valorRecebido?.toFixed(2) ?? null, valorLiquidadoCredito: c.valorLiquidadoCredito.toFixed(2), vencimento: c.vencimento.toISOString() }, calculo: { creditoAnterior: calc.creditoAnterior.toFixed(2), creditoNovo: calc.creditoNovo.toFixed(2) } };
}
async function revalidar(tx: Prisma.TransactionClient, p: { matriculaId: string; propostaAditivoId: string; conferenciaFinalId: string; versaoCondicoesId: string; cobrancaId: string; fotografiaHash: string; valorNovo: Prisma.Decimal; creditoAnterior: Prisma.Decimal; creditoNovo: Prisma.Decimal }) {
 const final = await tx.conferenciaFinalAditivo.findUniqueOrThrow({ where: { id: p.conferenciaFinalId }, select: { conclusaoId: true } });
 const estado = await carregarEstadoConferenciaFinalAditivoTx(tx, { matriculaId: p.matriculaId, propostaId: p.propostaAditivoId, conclusaoId: final.conclusaoId });
 const v = await tx.versaoCondicoesAditivo.findUniqueOrThrow({ where: { id: p.versaoCondicoesId }, select: { id: true, condicoesHash: true, conferenciaFinalId: true } });
 await tx.$queryRaw`SELECT id FROM "Cobranca" WHERE id=${p.cobrancaId} FOR UPDATE`; const c = await tx.cobranca.findUniqueOrThrow({ where: { id: p.cobrancaId } });
 if (v.conferenciaFinalId !== p.conferenciaFinalId || c.matriculaId !== p.matriculaId || c.tipo !== "MATRICULA") throw new ErroRegra("A fotografia não pertence mais ao aditivo e à taxa selecionados.");
 const anteriores = await tx.origemCreditoAcertoTaxaAditivo.aggregate({ where: { cobrancaId: c.id }, _sum: { valor: true } });
 const calc = calcularCreditoAcertoTaxa({ valorRecebido: c.valorRecebido, valorLiquidadoCredito: c.valorLiquidadoCredito, valorNovo: p.valorNovo, creditosTaxaJaOriginados: anteriores._sum.valor ?? 0 });
 if (calc.pendencia || !calc.creditoAnterior.eq(p.creditoAnterior) || !calc.creditoNovo.eq(p.creditoNovo) || hashSubstituicao(foto(estado, v, c, calc)) !== p.fotografiaHash) throw new ErroRegra("A fotografia do acerto ficou obsoleta; prepare novamente.");
 return c;
}

export async function proporAcertoTaxaAditivo(input: unknown) { return executarAcao(async () => {
 const autor = await exigirSessaoComPapel(Papel.FINANCEIRO), d = ProporAcertoTaxaSchema.parse(input);
 return prisma.$transaction(async tx => { await tx.$queryRaw`SELECT id FROM "Matricula" WHERE id=${d.matriculaId} FOR UPDATE`; await financeiro(tx, autor.id);
  const estado = await carregarEstadoConferenciaFinalAditivoTx(tx, { matriculaId: d.matriculaId, propostaId: d.propostaAditivoId, conclusaoId: d.conclusaoId });
  if (estado.revisaoHash !== d.revisaoHash || estado.dados.ambiente !== "PRODUCAO") throw new ErroRegra("A conclusão em produção e sua revisão exata são obrigatórias.");
  const v = await tx.versaoCondicoesAditivo.findFirst({ where: { matriculaId: d.matriculaId, propostaId: d.propostaAditivoId, conferenciaFinal: { conclusaoId: d.conclusaoId } }, orderBy: { versao: "desc" } });
  await tx.$queryRaw`SELECT id FROM "Cobranca" WHERE id=${d.cobrancaId} FOR UPDATE`; const c = await tx.cobranca.findFirst({ where: { id: d.cobrancaId, matriculaId: d.matriculaId, tipo: "MATRICULA" } }); if (!v || !c) throw new ErroRegra("Selecione uma cobrança de taxa real da matrícula.");
  const cond = v.condicoes as Record<string, any>, valor = cond.TAXA_VALOR?.valor ? new Prisma.Decimal(cond.TAXA_VALOR.valor) : c.valorNegociado, vencimento = cond.TAXA_VENCIMENTO?.data ? new Date(`${cond.TAXA_VENCIMENTO.data}T00:00:00.000Z`) : c.vencimento;
  const anteriores = await tx.origemCreditoAcertoTaxaAditivo.aggregate({ where: { cobrancaId: c.id }, _sum: { valor: true } }), calc = calcularCreditoAcertoTaxa({ valorRecebido: c.valorRecebido, valorLiquidadoCredito: c.valorLiquidadoCredito, valorNovo: valor, creditosTaxaJaOriginados: anteriores._sum.valor ?? 0 });
  if (calc.pendencia) throw new ErroRegra(`${calc.pendencia.tratamento} Valor a conciliar: ${calc.pendencia.valor.toFixed(2)}.`); const fotografia = foto(estado, v, c, calc), fotografiaHash = hashSubstituicao(fotografia);
  const repetida = await tx.propostaAcertoTaxaAditivo.findUnique({ where: { preparadorId_chaveIdempotencia: { preparadorId: autor.id, chaveIdempotencia: d.chaveIdempotencia } } }); if (repetida) { if (repetida.fotografiaHash !== fotografiaHash || repetida.motivo !== d.motivo || JSON.stringify(repetida.evidencia) !== JSON.stringify(d.evidencia)) throw new ErroRegra("A chave idempotente já foi usada com outra proposta."); return { id: repetida.id, status: repetida.status }; }
  const p = await tx.propostaAcertoTaxaAditivo.create({ data: { id: randomUUID(), matriculaId: d.matriculaId, propostaAditivoId: d.propostaAditivoId, conferenciaFinalId: v.conferenciaFinalId, versaoCondicoesId: v.id, cobrancaId: c.id, preparadorId: autor.id, valorNovo: valor, vencimentoNovo: vencimento, creditoAnterior: calc.creditoAnterior, creditoNovo: calc.creditoNovo, evidencia: d.evidencia as Prisma.InputJsonValue, motivo: d.motivo, fotografia: fotografia as Prisma.InputJsonValue, fotografiaHash, chaveIdempotencia: d.chaveIdempotencia } });
  await registrarEvento(tx, { tipo: "AcertoTaxaAditivoProposto", agregadoTipo: "Matricula", agregadoId: d.matriculaId, autorId: autor.id, payload: { propostaId: p.id, cobrancaId: c.id, fotografiaHash } }); return { id: p.id, status: p.status };
 });
}); }

export async function decidirAcertoTaxaAditivo(input: unknown) { return executarAcao(async () => {
 const autor = await exigirSessaoComPapel(Papel.FINANCEIRO), d = DecidirAcertoTaxaSchema.parse(input); return prisma.$transaction(async tx => { await financeiro(tx, autor.id, true); await tx.$queryRaw`SELECT id FROM "PropostaAcertoTaxaAditivo" WHERE id=${d.propostaId} FOR UPDATE`; let p = await tx.propostaAcertoTaxaAditivo.findUniqueOrThrow({ where: { id: d.propostaId }, include: { decisao: true } }); await tx.$queryRaw`SELECT id FROM "Matricula" WHERE id=${p.matriculaId} FOR UPDATE`; p = await tx.propostaAcertoTaxaAditivo.findUniqueOrThrow({ where: { id: d.propostaId }, include: { decisao: true } });
  if (p.preparadorId === autor.id) throw new ErroRegra("A decisão exige outro Financeiro."); if (p.decisao) { if (p.decisao.decisorId !== autor.id || p.decisao.aprovada !== d.aprovada || p.decisao.motivo !== d.motivo || p.decisao.chaveIdempotencia !== d.chaveIdempotencia) throw new ErroRegra("A proposta já recebeu outra decisão."); return { id: p.decisao.id, aprovada: p.decisao.aprovada }; } if (p.status !== "PENDENTE") throw new ErroRegra("A proposta não está pendente."); await revalidar(tx, p);
  const decisao = await tx.decisaoAcertoTaxaAditivo.create({ data: { id: randomUUID(), propostaId: p.id, decisorId: autor.id, aprovada: d.aprovada, motivo: d.motivo, fotografiaHash: p.fotografiaHash, chaveIdempotencia: d.chaveIdempotencia } }); await tx.propostaAcertoTaxaAditivo.update({ where: { id: p.id }, data: { status: d.aprovada ? "APROVADA" : "REJEITADA" } }); await registrarEvento(tx, { tipo: d.aprovada ? "AcertoTaxaAditivoAprovado" : "AcertoTaxaAditivoRejeitado", agregadoTipo: "Matricula", agregadoId: p.matriculaId, autorId: autor.id, payload: { propostaId: p.id, decisaoId: decisao.id, fotografiaHash: p.fotografiaHash } }); return { id: decisao.id, aprovada: decisao.aprovada };
 });
}); }

export async function aplicarAcertoTaxaAditivo(input: unknown) { return executarAcao(async () => {
 const autor = await exigirSessaoComPapel(Papel.FINANCEIRO), d = AplicarAcertoTaxaSchema.parse(input); return prisma.$transaction(async tx => { await financeiro(tx, autor.id, true); await tx.$queryRaw`SELECT id FROM "PropostaAcertoTaxaAditivo" WHERE id=${d.propostaId} FOR UPDATE`; let p = await tx.propostaAcertoTaxaAditivo.findUniqueOrThrow({ where: { id: d.propostaId }, include: { decisao: true, aplicacao: true } }); await tx.$queryRaw`SELECT id FROM "Matricula" WHERE id=${p.matriculaId} FOR UPDATE`; p = await tx.propostaAcertoTaxaAditivo.findUniqueOrThrow({ where: { id: d.propostaId }, include: { decisao: true, aplicacao: true } });
  if (p.aplicacao) { if (p.aplicacao.executorId !== autor.id) throw new ErroRegra("A proposta já recebeu outra aplicação."); return { id: p.aplicacao.id, aplicada: true }; } if (!p.decisao?.aprovada || p.decisao.decisorId !== autor.id || p.status !== "APROVADA") throw new ErroRegra("A aplicação exige decisão aprovada do executor independente."); const c = await revalidar(tx, p); await tx.$queryRaw`SELECT id FROM "Cobranca" WHERE id=${c.id} FOR UPDATE`;
  await tx.$queryRaw`SELECT id FROM "Comissao" WHERE "matriculaId"=${p.matriculaId} ORDER BY id FOR UPDATE`; const comissoes = await tx.comissao.findMany({ where: { matriculaId: p.matriculaId } });
  const app = await tx.aplicacaoAcertoTaxaAditivo.create({ data: { id: randomUUID(), propostaId: p.id, decisaoId: p.decisao.id, cobrancaId: c.id, executorId: autor.id, versaoAnterior: c.versao, valorAnterior: c.valorNegociado, valorNovo: p.valorNovo, vencimentoAnterior: c.vencimento, vencimentoNovo: p.vencimentoNovo, creditoAnterior: p.creditoAnterior, creditoNovo: p.creditoNovo, fotografia: p.fotografia as Prisma.InputJsonValue } }); const saldo = Prisma.Decimal.max(0, p.valorNovo.minus(c.valorRecebido ?? 0).minus(c.valorLiquidadoCredito)); await tx.cobranca.update({ where: { id: c.id }, data: { valorNegociado: p.valorNovo, vencimento: p.vencimentoNovo, saldo, status: saldo.isZero() ? "PAGO" : c.status === "PAGO" ? "PENDENTE" : c.status, versao: { increment: 1 } } });
  for (const comissao of comissoes) { if (comissao.tipo !== "PERCENTUAL" || !["PENDENTE", "APROVADA"].includes(comissao.status)) continue; const valor = new Prisma.Decimal(p.valorNovo).mul(comissao.percentual).div(100); await tx.comissao.update({ where: { id: comissao.id }, data: { valor, valorBase: p.valorNovo } }); await registrarEvento(tx, { tipo: "ComissaoRecalculada", agregadoTipo: "Comissao", agregadoId: comissao.id, autorId: autor.id, payload: { aplicacaoAcertoTaxaId: app.id, de: comissao.valor.toNumber(), para: valor.toNumber(), base: p.valorNovo.toNumber(), politicaId: comissao.politicaId } }); }
  if (p.creditoNovo.gt(0)) { const origem = await tx.origemCreditoAcertoTaxaAditivo.create({ data: { id: randomUUID(), aplicacaoId: app.id, matriculaId: p.matriculaId, cobrancaId: c.id, valor: p.creditoNovo, moeda: c.moeda, fotografia: p.fotografia as Prisma.InputJsonValue } }); await tx.creditoMatricula.create({ data: { matriculaId: p.matriculaId, moeda: c.moeda, valorInicial: p.creditoNovo, origemAcertoTaxaAditivoId: origem.id } }); }
  await tx.propostaAcertoTaxaAditivo.update({ where: { id: p.id }, data: { status: "APLICADA" } }); await registrarEvento(tx, { tipo: "AcertoTaxaAditivoAplicado", agregadoTipo: "Matricula", agregadoId: p.matriculaId, autorId: autor.id, payload: { propostaId: p.id, aplicacaoId: app.id, cobrancaId: c.id, fotografiaHash: p.fotografiaHash } }); return { id: app.id, aplicada: true };
 });
}); }
