import { Prisma } from "@prisma/client";
import { ErroRegra } from "@/server/_shared";
import { hashSubstituicao } from "./substituicao-estado";
import { validarValorAlteracaoAditivo } from "./aditivo-valores";

type Versao={id:string;versao:number;condicoes:Prisma.JsonValue;condicoesHash:string;vigenciaInicio:Date;aplicacao:{id:string}|null};
export function resolverHoraVigente(versoes:readonly Versao[],inicio:Date,fim:Date,valorHoraOriginal:string,moedaOriginal:string){
 if(fim<=inicio)throw new ErroRegra("Intervalo de horas inválido.");const efetiva=[...versoes].filter(v=>v.vigenciaInicio<=inicio).sort((a,b)=>b.vigenciaInicio.getTime()-a.vigenciaInicio.getTime()||b.versao-a.versao)[0];
 if(!Number.isFinite(inicio.getTime())||!Number.isFinite(fim.getTime()))throw new ErroRegra("Datas do intervalo inválidas.");const financeiro=(v:Versao)=>{if(hashSubstituicao(v.condicoes)!==v.condicoesHash||v.condicoes===null||Array.isArray(v.condicoes)||typeof v.condicoes!=="object")throw new ErroRegra("Condições formalizadas divergentes.");const c=v.condicoes as Record<string,unknown>;return hashSubstituicao({HORA_VALOR:c.HORA_VALOR??null,MOEDA:c.MOEDA??null,REGIME:c.REGIME??null});};const dentro=versoes.filter(v=>v.vigenciaInicio>inicio&&v.vigenciaInicio<fim),base=efetiva?financeiro(efetiva):hashSubstituicao({HORA_VALOR:null,MOEDA:null,REGIME:null}),mudancas=dentro.filter(v=>financeiro(v)!==base);if(mudancas.some(v=>!v.aplicacao))throw new ErroRegra("Há condições formalizadas pendentes de aplicação durante o intervalo de horas.");if(mudancas.length)throw new ErroRegra("Há mudança financeira formalizada durante o intervalo de horas.");
 if(!efetiva)return{valorHora:valorHoraOriginal,moeda:moedaOriginal,versaoAditivo:null};if(!efetiva.aplicacao)throw new ErroRegra("Condições formalizadas vigentes aguardam aplicação explícita.");financeiro(efetiva);const c=efetiva.condicoes as Record<string,unknown>;if(c.REGIME){const r=validarValorAlteracaoAditivo("REGIME",c.REGIME);if(r.tipo!=="REGIME"||r.regime!=="HORA_PARTICULAR")throw new ErroRegra("O regime formalizado não permite cobrança por hora.");}if(c.MOEDA){const m=validarValorAlteracaoAditivo("MOEDA",c.MOEDA);if(m.tipo!=="MOEDA"||m.moeda!==moedaOriginal)throw new ErroRegra("Mudança de moeda exige fluxo específico antes do cálculo por hora.");}const h=c.HORA_VALOR?validarValorAlteracaoAditivo("HORA_VALOR",c.HORA_VALOR):null;if(h&&h.tipo!=="DINHEIRO")throw new ErroRegra("Valor por hora formalizado inválido.");if(h?.tipo==="DINHEIRO"&&h.moeda!==moedaOriginal)throw new ErroRegra("Valor por hora usa moeda incompatível.");return{valorHora:h?.tipo==="DINHEIRO"?h.valor:valorHoraOriginal,moeda:moedaOriginal,versaoAditivo:{id:efetiva.id,versao:efetiva.versao,condicoesHash:efetiva.condicoesHash}};
}
export async function resolverHoraVigenteTx(tx:Prisma.TransactionClient,input:{matriculaId:string;inicio:Date;fim:Date;valorHoraOriginal:string;moedaOriginal:string}){const v=await tx.versaoCondicoesAditivo.findMany({where:{matriculaId:input.matriculaId,vigenciaInicio:{lt:input.fim}},select:{id:true,versao:true,condicoes:true,condicoesHash:true,vigenciaInicio:true,aplicacao:{select:{id:true}}}});return resolverHoraVigente(v,input.inicio,input.fim,input.valorHoraOriginal,input.moedaOriginal);}
