import { describe, expect, it } from "vitest";
import { planejarEfeitosAditivo } from "./aditivo-efeitos";
describe("planejarEfeitosAditivo",()=>{
 it("não interpreta valor legado",()=>expect(planejarEfeitosAditivo([{origem:"ALUNO_NOME",novo:"Ana"}])).toEqual({efeitos:[],pendencias:[{origem:"ALUNO_NOME",mensagem:"O valor é textual legado e precisa ser estruturado antes de planejar efeitos."}]}));
 it("projeta condição e acerto somente com contexto real",()=>{const a=[{origem:"MENSALIDADE_VALOR",novo:"20.00 BRL",valorEstruturado:{tipo:"DINHEIRO" as const,valor:"20",moeda:"BRL"}}];expect(planejarEfeitosAditivo(a).pendencias[0]?.mensagem).toMatch(/Confira se há/);expect(planejarEfeitosAditivo(a,{cobrancaEmitida:false}).pendencias).toEqual([]);const r=planejarEfeitosAditivo(a,{cobrancaEmitida:true});expect(r.efeitos.map(e=>[e.dominio,e.exigeAcerto])).toEqual([["CONDICOES_FUTURAS",undefined],["COBRANCA_EMITIDA",true]]);expect(r.pendencias[0]?.mensagem).toMatch(/Selecione/);});
 it("mantém agenda pendente",()=>expect(planejarEfeitosAditivo([{origem:"AGENDA_PARTICULAR",novo:"a",valorEstruturado:{tipo:"AGENDA",propostaAgendaId:"p"}}]).pendencias[0]?.mensagem).toMatch(/resolução/));
 it("não projeta cadastro global e recusa duplicidade",()=>{const r=planejarEfeitosAditivo([{origem:"ALUNO_NOME",novo:"Ana",valorEstruturado:{tipo:"TEXT",texto:"Ana"}}]);expect(r.efeitos[0]?.destino).toBe("matricula.cadastroContratual.aluno.nome");expect(()=>planejarEfeitosAditivo([{origem:"ALUNO_NOME",novo:"Ana",valorEstruturado:{tipo:"TEXT",texto:"Ana"}},{origem:"ALUNO_NOME",novo:"Ana",valorEstruturado:{tipo:"TEXT",texto:"Ana"}}])).toThrow(/repetida/);});
 it("deixa divergência textual como pendência",()=>expect(planejarEfeitosAditivo([{origem:"MOEDA",novo:"Real",valorEstruturado:{tipo:"MOEDA",moeda:"BRL"}}]).pendencias[0]?.mensagem).toMatch(/diverge/));
});
