"use server";
import { projetarCadastroContratual } from "./cadastro-contratual";
import { Papel } from "@prisma/client";import { z } from "zod";import { prisma } from "@/lib/prisma";import { executarAcao,exigirSessaoComPapel,ErroRegra } from "@/server/_shared";import { aplicarCondicoesFormalizadasAditivoTx, registrarCondicoesFormalizadasAditivoTx } from "./aditivo-condicoes-tx";import { hashSubstituicao } from "./substituicao-estado";
const id=z.string().min(1).max(100),Registro=z.object({matriculaId:id,propostaId:id,conclusaoId:id,revisaoHash:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const Aplicacao=Registro.extend({chaveIdempotencia:z.string().trim().min(1).max(200)}).strict();
export async function registrarCondicoesFormalizadasAditivo(input:z.input<typeof Registro>){return executarAcao(async()=>{const a=await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA),d=Registro.parse(input);return prisma.$transaction(tx=>registrarCondicoesFormalizadasAditivoTx(tx,a.id,d),{timeout:30000});});}
export async function aplicarCondicoesFormalizadasAditivo(input:z.input<typeof Aplicacao>){return executarAcao(async()=>{const a=await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA),d=Aplicacao.parse(input);return prisma.$transaction(tx=>aplicarCondicoesFormalizadasAditivoTx(tx,a.id,d),{timeout:30000});});}
export async function formalizarEAplicarCondicoesAditivo(input:z.input<typeof Aplicacao>){return executarAcao(async()=>{const a=await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA),d=Aplicacao.parse(input);const formalizacao={matriculaId:d.matriculaId,propostaId:d.propostaId,conclusaoId:d.conclusaoId,revisaoHash:d.revisaoHash};return prisma.$transaction(async tx=>{const versao=await tx.versaoCondicoesAditivo.findUnique({where:{propostaId:d.propostaId},select:{id:true}});if(!versao)await registrarCondicoesFormalizadasAditivoTx(tx,a.id,formalizacao);return aplicarCondicoesFormalizadasAditivoTx(tx,a.id,d);},{timeout:30000});});}
export async function consultarCondicoesAditivo(input:{matriculaId:string;em:string}){return executarAcao(async()=>{const a=await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA),d=z.object({matriculaId:id,em:z.string().datetime({offset:true})}).strict().parse(input);return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Usuario" WHERE id=${a.id} FOR SHARE`;const u=await tx.usuario.findUnique({where:{id:a.id},select:{ativo:true,papeis:true}});if(!u?.ativo||!u.papeis.some(p=>p===Papel.SECRETARIA_ACADEMICA||p===Papel.ADMINISTRADOR))throw new ErroRegra("Permissão de Secretaria necessária.");if(!await tx.matricula.count({where:{id:d.matriculaId}}))throw new ErroRegra("Matrícula não encontrada.");const v=await tx.versaoCondicoesAditivo.findFirst({where:{matriculaId:d.matriculaId,vigenciaInicio:{lte:new Date(d.em)}},orderBy:[{vigenciaInicio:"desc"},{versao:"desc"}],select:{id:true,propostaId:true,versao:true,condicoes:true,condicoesHash:true,vigenciaInicio:true,registradaEm:true,aplicacao:{select:{id:true,autorId:true,revisaoHash:true,condicoesHash:true,aplicadaEm:true}}}});if(!v)return null;if(hashSubstituicao(v.condicoes)!==v.condicoesHash)throw new ErroRegra("Condições formalizadas divergentes.");return v;});});}
export async function consultarAplicacaoCondicoesAditivo(input:{matriculaId:string;propostaId:string}){return executarAcao(async()=>{const a=await exigirSessaoComPapel(Papel.SECRETARIA_ACADEMICA),d=z.object({matriculaId:id,propostaId:id}).strict().parse(input);return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Usuario" WHERE id=${a.id} FOR SHARE`;const u=await tx.usuario.findUnique({where:{id:a.id},select:{ativo:true,papeis:true}});if(!u?.ativo||!u.papeis.some(p=>p===Papel.SECRETARIA_ACADEMICA||p===Papel.ADMINISTRADOR))throw new ErroRegra("Permissão de Secretaria necessária.");const v=await tx.versaoCondicoesAditivo.findFirst({where:{matriculaId:d.matriculaId,propostaId:d.propostaId},select:{id:true,matriculaId:true,propostaId:true,versao:true,condicoes:true,condicoesHash:true,vigenciaInicio:true,aplicacao:{select:{id:true,aplicadaEm:true,condicoesHash:true}}}});if(!v)return null;if(hashSubstituicao(v.condicoes)!==v.condicoesHash)throw new ErroRegra("Condições formalizadas divergentes.");return { ...v, cadastroContratual: projetarCadastroContratual(d.matriculaId, v, new Date()) };});});}
