import { describe, expect, it } from "vitest";
import { fotografiaCanonicaAgendaAditivo, hashPropostaAgendaAditivo, PrepararAgendaAditivoSchema, PropostaAgendaAditivoSchema, textoAgendaAditivo } from "./agenda-aditivo-schema";
const base = { matriculaId: "m", preparadorId: "u", fonteContratualId: "fonte", fonteContratualHash: "a".repeat(64), contexto: { calendarioId: "cal", calendarioVersao: 1, fusoInstitucional: "America/Sao_Paulo", aditivos: [] }, encontros: [{ encontroId: "e1", professorAnteriorId: "p1", professorAnteriorNome: "Ana", professorNovoId: "p2", professorNovoNome: "Bia", inicioAnterior: "2099-10-01T15:00:00-03:00", fimAnterior: "2099-10-01T16:00:00-03:00", inicioNovo: "2099-10-02T15:00:00-03:00", fimNovo: "2099-10-02T16:00:00-03:00", duracaoMinutos: 60, fusoAnterior: "America/Sao_Paulo", fusoNovo: "America/Sao_Paulo" }] };
describe("fotografia de agenda de aditivo", () => {
 it("preserva conjunto explícito, hash canônico e antes/depois legível", () => { const p = PropostaAgendaAditivoSchema.parse(base), texto = textoAgendaAditivo(p); expect(hashPropostaAgendaAditivo(p)).toBe(hashPropostaAgendaAditivo({ ...p, encontros: [{ ...p.encontros[0], inicioNovo: "2099-10-02T18:00:00Z", fimNovo: "2099-10-02T19:00:00Z" }] })); expect(hashPropostaAgendaAditivo(p)).not.toBe(hashPropostaAgendaAditivo({ ...p, encontros: [{ ...p.encontros[0], professorNovoNome: "Clara" }] })); expect(texto).toContain("Ana"); expect(texto).toContain("Bia"); expect(texto).toContain("02/10/2099"); expect(texto).toContain("America/Sao_Paulo"); });
 it("recusa conjunto e horários inválidos", () => { expect(() => PropostaAgendaAditivoSchema.parse({ ...base, encontros: [base.encontros[0], base.encontros[0]] })).toThrow(/uma vez/); expect(() => PropostaAgendaAditivoSchema.parse({ ...base, encontros: [{ ...base.encontros[0], duracaoMinutos: 30 }] })).toThrow(/duração/); expect(() => PropostaAgendaAditivoSchema.parse({ ...base, encontros: [{ ...base.encontros[0], fimAnterior: base.encontros[0].inicioAnterior }] })).toThrow(/original/); expect(() => PropostaAgendaAditivoSchema.parse({ ...base, encontros: [{ ...base.encontros[0], fusoOrigem: "fuso-invalido" }] })).toThrow(); });
 it("normaliza ordem e valida o comando sem autoridade interna", () => { const segundo={...base.encontros[0],encontroId:"e2",inicioNovo:"2099-10-02T23:30:00-03:00",fimNovo:"2099-10-03T00:30:00-03:00"}, cliente={matriculaId:"m",encontros:[{encontroId:"e",professorNovoId:"p",inicioNovo:"2099-10-01T15:00:00-03:00",fimNovo:"2099-10-01T16:00:00-03:00",duracaoMinutos:60,fusoOrigem:"America/Sao_Paulo"}]}; expect(fotografiaCanonicaAgendaAditivo({...base,encontros:[segundo,base.encontros[0]]}).encontros.map(e=>e.encontroId)).toEqual(["e1","e2"]); const texto=textoAgendaAditivo({...base,encontros:[segundo]});expect(texto).toContain("02/10/2099");expect(texto).toContain("03/10/2099");expect(PrepararAgendaAditivoSchema.parse(cliente)).toEqual(cliente);expect(()=>PrepararAgendaAditivoSchema.parse({...cliente,preparadorId:"u"})).toThrow();expect(()=>PrepararAgendaAditivoSchema.parse({...cliente,encontros:[{...cliente.encontros[0],duracaoMinutos:30}]})).toThrow(/duração/); });
 it("aceita alteração de duração de 90 para 60 minutos", () => expect(PropostaAgendaAditivoSchema.parse({ ...base, encontros: [{ ...base.encontros[0], fimAnterior: "2099-10-01T16:30:00-03:00" }] }).encontros[0].duracaoMinutos).toBe(60));
});
