import { afterEach, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({propor:vi.fn(),decidir:vi.fn(),useState:vi.fn(),useRef:vi.fn(),refresh:vi.fn()}));
vi.mock("react",async original=>({...await original<typeof import("react")>(),useState:mocks.useState,useRef:mocks.useRef})); vi.mock("next/navigation",()=>({useRouter:()=>({refresh:mocks.refresh})})); vi.mock("@/server/migracao/presenca-historica",()=>({proporPresencaHistoricaMigracao:mocks.propor,decidirPresencaHistoricaMigracao:mocks.decidir}));
import { PresencaHistorica } from "./PresencaHistorica";
type No={type?:unknown;props?:Record<string,unknown>}; type EventoFormulario={preventDefault():void;currentTarget:object}; function encontrar(no:unknown,tipo:string):No|undefined{if(Array.isArray(no))return no.map(x=>encontrar(x,tipo)).find(Boolean);if(!no||typeof no!=="object")return;const n=no as No;if(n.type===tipo)return n;return encontrar(n.props?.children,tipo)}
function montar(ocupado=false){const erro=vi.fn(),ok=vi.fn(),setOcupado=vi.fn(),chave={current:null as string|null};mocks.useState.mockReset().mockReturnValueOnce([ocupado,setOcupado]).mockReturnValueOnce([null,erro]).mockReturnValueOnce([null,ok]).mockReturnValueOnce([false,vi.fn()]).mockReturnValueOnce([null,vi.fn()]);mocks.useRef.mockReset().mockReturnValue(chave);const a=PresencaHistorica({linhaId:"linha",aulas:[{id:"aula",ocorridaEm:"2025-02-10T00:00:00.000Z",conteudo:"Conteúdo",turma:"Turma"}],propostas:[],podePropor:true,podeDecidir:false,atorId:"secretaria"});return{form:encontrar(a,"form")!.props!,fieldset:encontrar(a,"fieldset")!.props!,erro,ok,setOcupado,chave};}
afterEach(()=>vi.unstubAllGlobals());
it("envia aula escolhida, presença e evidência, bloqueando e repetindo a chave",async()=>{vi.stubGlobal("crypto",{randomUUID:()=>"00000000-0000-4000-8000-000000000203"});vi.stubGlobal("FormData",class{get(n:string){return({aulaId:"aula",presencaOrigemId:"origem-1",participacao:"PRESENTE",evidencia:"planilha!2"}as Record<string,string>)[n]??null}});mocks.propor.mockResolvedValue({ok:true,dado:{repetida:false}});const c=montar();const e:EventoFormulario={preventDefault:vi.fn(),currentTarget:{}};(c.form.onSubmit as (evento:EventoFormulario)=>void)(e);await Promise.resolve();expect(mocks.propor).toHaveBeenCalledWith({linhaId:"linha",aulaId:"aula",presencaOrigemId:"origem-1",participacao:"PRESENTE",evidencia:{referencia:"planilha!2"},chaveIdempotencia:"00000000-0000-4000-8000-000000000203"});expect(c.setOcupado).toHaveBeenCalledWith(true);expect(c.setOcupado).toHaveBeenLastCalledWith(false);(c.form.onSubmit as (evento:EventoFormulario)=>void)(e);await Promise.resolve();expect(mocks.propor.mock.calls[1]?.[0].chaveIdempotencia).toBe(mocks.propor.mock.calls[0]?.[0].chaveIdempotencia);expect(montar(true).fieldset.disabled).toBe(true);});
it("mostra falha sem atualizar a tela",async()=>{mocks.refresh.mockReset();vi.stubGlobal("crypto",{randomUUID:()=>"00000000-0000-4000-8000-000000000204"});vi.stubGlobal("FormData",class{get(n:string){return({aulaId:"aula",presencaOrigemId:"origem-1",participacao:"FALTA",evidencia:"planilha!2"}as Record<string,string>)[n]??null}});mocks.propor.mockResolvedValue({ok:false,erro:"Fonte mudou"});const c=montar();(c.form.onSubmit as (e:{preventDefault():void;currentTarget:object})=>void)({preventDefault:vi.fn(),currentTarget:{}});await Promise.resolve();expect(c.erro).toHaveBeenCalledWith("Fonte mudou");expect(mocks.refresh).not.toHaveBeenCalled();});
